### ISSUE TITLE
Move split

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#10]
Счас сплиттер считается как `поз=поз*1.05`.. ? тогда это гео прогрессия
а лучше делать ари прогрессию
`поз=поз + 0.05*размер_панели`

**Comment by kvichans** [comment]
Делал специально как гео.
Могу добавить доп.новые методы для арифм перемещения
Будете пользоваться?

**Comment by Alexey-T** [comment]
нет-не буду.
