### ISSUE TITLE
Need app_idle

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#100]
Open files in dir and all subdirs-- выбрал ННН файлов, октрываются. после 5сек такого ОС Лин показывает "программа не отвечает. убить?". 
Надо- каждые ~10 файлов или ~2-3 сек вызывать в цикле app_idle.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Win только показывает в титуле "Не отвечает". Убить предлагает лишь при попытке закрыть окно.

**Comment by kvichans** [comment]
Не сделано

**Comment by Alexey-T** [comment]
was fixed in 1.5.04
