### ISSUE TITLE
New find dlg

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#106]
Добавилась команда
![default](https://user-images.githubusercontent.com/7419630/40425297-a9478f0a-5ea0-11e8-860d-09e046307574.png)
которая запускает такой диалог
![default](https://user-images.githubusercontent.com/7419630/40425378-df32ccd8-5ea0-11e8-99f2-666fd1a0d294.png)
Три левые кнопки имеют такой же смысл, как в Поиске и ФИФ.
Дальше комбо для ввода условия поиска и `=` для вызова меню.
![default](https://user-images.githubusercontent.com/7419630/40425458-198914fa-5ea1-11e8-8cc7-5bdc3c1db984.png)

После `Enter` находятся все подходящие фрагменты, выделяется тот, что находится за первой кареткой и в титуле диалога отображается статистика
![default](https://user-images.githubusercontent.com/7419630/40425613-96098c4e-5ea1-11e8-9d7c-b311d8d80c70.png)
Дальше `Enter` выделяет следующий фрагмент, `Shift+Enter` - предыдущий. Оба работают по циклу.

Последняя команда в меню позволяет при закрытии диалога восстановить каретку/выделение, которое было перед вызовом.

---
Можно тестировать из ГХ

**Comment by kvichans** [comment]
Диалог будет хранить состояния кнопок и историю запросов в `user.json` в ключе
`cuda_ext.find.find_in_lines`

**Comment by Alexey-T** [comment]
Лучше хранить в history*.json

**Comment by Alexey-T** [comment]
не понял смысла. то же делает и обычный поиск.

**Comment by kvichans** [comment]
Как не что-то хранить в  history*.json? Как это читать/писать?

**Comment by Alexey-T** [comment]
History.json - можно писать в любой новый ключ, или лучше в ключ plugins для всех плагинов

**Comment by kvichans** [comment]
Нужно договориться о разделении полномочий при использовании history.json.
- В какой момент сам Куд его читает и пишет? 
- Нет ли риска у Куд или плагина потерять данные из-за того, что history.json позже перезапишут?

**Comment by Alexey-T** [comment]
Хм, всетаки не надо в него. оставим его Куд. и не user.json тоже. введите 'history plugins.json'

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Обновление в ГХ
Теперь диалог хранит свои данные в `settings\plugin history.json`

**Comment by kvichans** [comment]
Обновление в ГХ
Теперь можно переключать опцию `Instant search`
![default](https://user-images.githubusercontent.com/7419630/40620751-9ac67f1c-62a2-11e8-8283-15636bd0864c.png)
- Диалог сам перевызывается и показывает либо комбо, либо едит.
- При `Instant search` поиск выполняется (1) после каждого изменения, (2) при вызове диалога, если из таба переносится выделение

**Comment by Alexey-T** [comment]
хорошо, теперь больше похоже на quick search.

**Comment by kvichans** [comment]
Может быть ограничить запуск instant-поиска - не начинать искать, пока не введено 3 символа?

**Comment by Alexey-T** [comment]
по опции можно, по числу символов.

**Comment by kvichans** [comment]
Выложил в ГХ
Готов публиковать. Может еще текст где поправить?

**Comment by Alexey-T** [comment]
"immediately" typo
"Command 'Restore starting selection" в хелпе- "... initial selection"
"will update" в  хелпе -> "will be updated"

**Comment by Alexey-T** [comment]
"minumum" typo

**Comment by Alexey-T** [comment]
Если в длг "instant srch min"  нажать отмену- креш

**Comment by kvichans** [comment]
Поправил
Добавил Shift+Esc для закрытия с восстановлением каретки
Выложил в ГХ и опубликовал
