### ISSUE TITLE
Need cmd "Edit stream comment chars for lexer"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#11]
Пригодится если нужно для лекса задать символ комента ()
и не лазить в файл .cfg

**Comment by kvichans** [comment]
Как это реализовать?
Пользователю нужно предъявить прежний *коммент* - как его извлечь?
От пользователя придет новый - как его внедрить?

**Comment by Alexey-T** [comment]
Прочитать файл - записать файл https://github.com/Alexey-T/CudaText/blob/master/app/settings_default/default_lexers.json

**Comment by kvichans** [comment]
А-а-а. Вспомнил, я же этот файл уже разбирал. 
А Куд его не кэширует? Не может быть такого, что плагин изменит файл, а Куд продолжит со старыми настройками?

**Comment by kvichans** [comment]
А разве можно править файл из папки settings_default ?

**Comment by Alexey-T** [comment]
1- Кеширует или нет- код чтения комемнтов ваш. вроде бы? он в cudax_lib? 2- править settings_def низя, так что надо писать в settings/lexers_user.json

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Готово

**Comment by Alexey-T** [comment]
Спасиб

**Comment by Alexey-T** [comment]
не по гайду? немного 
![cmt](https://cloud.githubusercontent.com/assets/4154978/12512906/f4def936-c12b-11e5-8451-809c651e846b.png)

**Comment by kvichans** [comment]
В гайде еще нет рекомендаций для вертикального расположения edit.
Да, вижу, что слипаются

**Comment by Alexey-T** [comment]
(там еще check надо опустить на 2,он при выделении слипается)

**Comment by kvichans** [comment]
fix
