### ISSUE TITLE
Beta with "go back" comands

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#110]
Обе команды "go back"
`Tabs \ Choose previously active tab to activate (go back)`
`Tabs \ Activate previously active tab (go back)`
переделаны с `on_focus` на `PROP_ACTIVATION_TIME`

@Alexey-T  Желательно потестировать на последней сборке Куд, чтобы проверить
- Вызов этих команд сразу после запуска Куд
- Переходы на все панели (на Дерево у меня еще не работает)

**Comment by Alexey-T** [comment]
click or dbl-click - должны выбирать п-т листбокса (закрывать д.)

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
простые стрелки хорошо бы ходили влево-вправо.
и Enter - выбор.

**Comment by kvichans** [comment]
Уже так и работает

**Comment by kvichans** [comment]
Публиковать?

**Comment by Alexey-T** [comment]
публиковать

**Comment by kvichans** [comment]
Уже опубликовал 18 сентября
