### ISSUE TITLE
Choose tab to switch to - crash with empty tabs

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#114]
6 empty tabs (no files).
crash.

![tab-sw-er](https://user-images.githubusercontent.com/4154978/44745427-61985600-ab10-11e8-814e-1e3b44daf296.png)

ver 1.5.18

**Comment by kvichans** [comment]
Мой косяк - забыл обновить файл в zip.
Только без него свичер вообще не должен работать.

Обновил zip на СФ без подъема версии.
Лучше?

**Comment by Alexey-T** [comment]
да- спасибо
