### ISSUE TITLE
Tab swicher cannot switch to 1st tab

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#115]
seems Prop_activaation_time not inited?
Untitled1 tab not shown in list.

![sw-bug](https://user-images.githubusercontent.com/4154978/44794065-5a288980-abb0-11e8-858f-7fd79e9f4b53.png)

**Comment by kvichans** [comment]
Да, это недостаток Куд: не проставляется *тик* для таба, который получает фокус при запуске

**Comment by kvichans** [comment]
Событие on_focus для него тоже не генерится

**Comment by Alexey-T** [comment]
хоть и нет тика но сам таб доступен , и надо его все равно показать, неважно какой там тик.

**Comment by Alexey-T** [comment]
а их нужно всегда показывать- все табы из текущей группы. иначе свичер недоделка. Если тик 0- показать в кконце списка.

**Comment by kvichans** [comment]
Нет - так я делать не буду

**Comment by kvichans** [comment]
Сейчас есть заплатка. Если у всех табов тик нулевой, то показываю текущий.
Нужно чтобы Куд ставил тому табу, в котором оказался пользователь при запуске правильный тик - это решит проблему

**Comment by Alexey-T** [comment]
жалко =(

**Comment by Alexey-T** [comment]
мы это решили, закрою?
