### ISSUE TITLE
Center cmd

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#12]
Команду простую хочется

- Center current line on screen- центрировать строку верхней каретки чтобы каретка была тамже но скролл поменялся- строка каретки стала бы  по центру
(потестить на конце и начале файла)

**Comment by kvichans** [comment]
Да, хорошая команда
todo

**Comment by kvichans** [comment]
Что-то пошло не так.
При выполнении `ed.set_top(10+ed.get_top())` из плагина или из консоли проявляется странный эффект
- скролл не меняется сразу после выполнения `ed.set_top(10+ed.get_top())`
- при перемещениях каретки все еще сохраняется старый скролл
- при любом изменении текста происходит сдвиг на 10 строк

**Comment by kvichans** [comment]
Как узнать сколько строк помещается на экран?

**Comment by Alexey-T** [comment]
добавил
>>> =ed.get_prop(PROP_VISIBLE_LINES)
14
>>> =ed.get_prop(PROP_VISIBLE_COLUMNS)
135

**Comment by kvichans** [comment]
Спасибо. Я сам 3(!) раза просмотрел список констант ed.get_prop и не видел :)

**Comment by kvichans** [comment]
А-а-а, так это новые свойства! Вот почему я их не видел :)

**Comment by Alexey-T** [comment]
Да новые

**Comment by kvichans** [comment]
Жду бету

**Comment by kvichans** [comment]
Готово

**Comment by Alexey-T** [comment]
Ок-спасибо..
