### ISSUE TITLE
Narrow dialog Rename

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#121]
чего такой мелкий диалог? имя не влезло
 
![screenshot from 2018-12-05 22-09-04](https://user-images.githubusercontent.com/4154978/49537631-87d14d00-f8da-11e8-8ae0-26222c8174c6.png)

**Comment by Alexey-T** [comment]
а почему .html тут в ДВУХ полях?

**Comment by Alexey-T** [comment]
можно раза в 1.5 шире.

**Comment by Alexey-T** [comment]
:-(

**Comment by Alexey-T** [comment]
ваши константы Dlg_w/h тоже бестолковые, не использованы

**Comment by kvichans** [comment]
Оба мы бестолковые :)
Поменяю реализацию с `dlg_custom` на `dlg_proc` и будет изменяемая ширина

**Comment by Alexey-T** [comment]
Мой патч в рамках вашего кода

**Comment by kvichans** [comment]
Критиковал не патч (он правильный), а ТЗ: фиксировано растянуть диалог - не решение

**Comment by kvichans** [comment]
Бета в ГХ

**Comment by kvichans** [comment]
Ширину поправил
Как убрать кнопку не знаю

**Comment by kvichans** [comment]
Насколько помню (проходили это на ПоискПоСтрокам) если убрать кнопки min+max, то диалог теряет resize

**Comment by Alexey-T** [comment]
спасибо, поправили.
