### ISSUE TITLE
Group commands needed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#124]
Такие кмд есть в VSCode.  
 
- focus group 1....6 
- focus group floating-1, floating-2, floating-3 (это не в Code, это я уже пишу)

**Comment by kvichans** [comment]
Не понятно. Опишите подробнее

**Comment by Alexey-T** [comment]
я подумал что это wish к Куде а не к вам, команды лучше в куде будут. закроем
