### ISSUE TITLE
Wish- Align lines by separator

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#13]
Команда нужна часто. еще в Син просили раза 2. и сам пользуюсь

- вводим separator char (пример для питона- "=")
- выделенные строки (можно юзать 1 выделение) меняются пробелами - символ "=" должен быть в них в одной колонке

~~~
aa = 1
aaaa = 2
aaaaaaaaaa = 3
bbb
cccc
ddd = 4
~~~
==>

~~~
aa         = 1
aaaa       = 2
aaaaaaaaaa = 3
bbb
cccc
ddd        = 4
~~~

**Comment by kvichans** [comment]
Зачетно
todo

**Comment by kvichans** [comment]
Как в Син команда называется/вызывается?
Параметр "сепаратор" при каждом вызове запрашивается или храниться в конфиге?

**Comment by kvichans** [comment]
Уже нашел. Запрашивается перед в каждом запуске

**Comment by Alexey-T** [comment]
Except если отменить диалог dlg-input

**Comment by kvichans** [comment]
Да, прошляпил None из dlg_input
fix

**Comment by Alexey-T** [comment]
На питоне красиво+коротко (делал па пас)
