### ISSUE TITLE
Bad reload tree

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#131]
Def tree_items_to_list
Пуск команды treeupdate идёт внутри рекурсии, не ок. Надо один раз перечитать до начала рекурсии

**Comment by kvichans** [comment]
Не поняли код.
Процедура `tree_items_to_list` (да она рекурсивная) завершается (стр 123) и **потом** начинается бесконечный цикл для первого входа в `tree_items_to_list` и показа `dlg_menu`.

**Comment by Alexey-T** [comment]
внутри нее есть
```
            if not nodes:
                ed.cmd(cmds.cmd_TreeUpdate)
                nodes = app.tree_proc(h_tree, app.TREE_ITEM_ENUM, id_node)
                if not nodes:
                    return 
```
когда она входит в пустой узел, она обновляет дерево- что не надо делать для К пустых узлов дерева

**Comment by kvichans** [comment]
Аааа. Не заметил этот рудимент. 
Убрал
Опубликую

**Comment by kvichans** [comment]
Опубликовал. Не стал наращивать версию.

**Comment by Alexey-T** [comment]
забыли push to GH?
