### ISSUE TITLE
FindInLines docked, must use current UI theme

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#134]
now it's white on black Cuda.
![Screenshot from 2019-04-15 16-10-58](https://user-images.githubusercontent.com/4154978/56135332-25c7d900-5f99-11e9-9704-1bc54471bf2a.png)

**Comment by kvichans** [comment]
Это для кого? Будет АПИ для применения темы к формам?

**Comment by Alexey-T** [comment]
Для вас. Читать цвета темы уже можно . App_proc. Ставить тематические кнопки тоже можно. Менять цвет формы можно

**Comment by kvichans** [comment]
Где это можно увидеть в действии?

**Comment by Alexey-T** [comment]
нигде

**Comment by Alexey-T** [comment]
Ставить кнопки- ставите контрол button_ex

**Comment by dinkumoil** [comment]
@kvichans 

Would be nice to have a themed dialog, at least when docked.

**Comment by kvichans** [comment]
It's too hard. I'm not ready to rewrite GUI.
IMHO: CT API must to solve the problem
