### ISSUE TITLE
rename file - not works on my side

### ISSUE THREAD

**Issue by MiroslavMatas** [kvichans/cuda_ext#139]
something is wrong… cudatext 1.84.0, rename file not lead to success…
TIA
Miro

**Comment by kvichans** [comment]
Please more details

**Comment by Alexey-T** [comment]
OS
Full file name 
Version of plugin

**Comment by MiroslavMatas** [comment]
download cudatext-win-x64-1.84.0.0.zip, unzip to some temp folder, run + add install cudaext, restart cudatext, create new file + save, cudaext command: rename file - no change

**Comment by kvichans** [comment]
See _rerpro_.
Wait.

**Comment by Alexey-T** [comment]
Правильно писать I see repro- иначе это «смотри репро»

**Comment by kvichans** [comment]
**Miro**
Update plug via AddonManager

**Comment by MiroslavMatas** [comment]
thanks a lot
have a nice day
