### ISSUE TITLE
Feature Find/Replace -> Find "in lines" doesn't work correctly with docked dialog

### ISSUE THREAD

**Issue by dinkumoil** [kvichans/cuda_ext#140]
# Steps to reproduce

1. Open an arbitrary file.
2. Go to `(menu) Plugins -> Cuda-Ext -> Find/Replace -> Find "in lines"`. => Floating dialog is shown.
3. Click on `=` button to open menu.
4. Check option `Dock to window bottom (close dialog)`.
5. Go to `(menu) Plugins -> Cuda-Ext -> Find/Replace -> Find "in lines"`. => Docked dialog is shown above status bar.
6. Click in **left** edit field and start typing a word that you know for sure is contained in the opened file.

# Expected behaviour

Search should start after typing 3rd character and first occurence of typed word should be selected.

# Actual behaviour

Nothing happens. Only after typing some characters into the **right** edit field, going back to the **left** edit field and typing arbitrary characters, the word contained in the **right** edit field is been searched for.

This buggy behaviour  **only** occurs when the _Find "in lines"_ dialog is docked, no matter whether at window bottom or at window top.

**Comment by kvichans** [comment]
Try to use

**Comment by Alexey-T** [comment]
Ie, install CudaExt from GitHub (delete normal version first).

**Comment by kvichans** [comment]
Or update with CT AddonMan

**Comment by dinkumoil** [comment]
Searching for the content of the left edit field works now. But there is a new bug now.

When I press `SHIFT+TAB` (_CudaText_ core tab switcher) the active tab is switched to the tab at the right of the original tab, but the file's content is not visible. Subsequent pressing of `SHIFT+TAB` does nothing, tab is not switched anymore. It's the same with `CTRL+SHIFT+TAB` (switching to the tab at the left of the original tab).

When I click on `(menu) Plugins -> Cuda-Ext -> Tabs -> Activate next tab (global loop)` (_Cuda-Ext_ tab switcher) the active tab is switched to the tab at the right of the original tab, but the file's content is not visible. Subsequent clicks to this menu entry change the active tab but the related file's content is never visible. It's the same with `(menu) Plugins -> Cuda-Ext -> Tabs -> Activate previous tab (global loop)` and also with  `(menu) Plugins -> Cuda-Ext -> Tabs -> Activate previously active tab (go back)`.

To be able to switch tabs again (when using _CudaText_ core tab switcher) and to see the related file's content, the docked _Find "in lines"_ dialog has to be closed.

**Comment by kvichans** [comment]
> Shift+Tab switches active tab but not focus in FiL.

No repro in my CT on Win10: `Shift+Tab` move focus from **left** edit to button `"w"`.
@Alexey-T Do you have repro on Mac/Lin?

**Comment by dinkumoil** [comment]
@kvichans 

I edited my comment multiple times, sorry. Please reread current version. You have to focus a tab before trying to use tab switcher (CT core ore _Cuda-Ext_).

**Comment by kvichans** [comment]
@dinkumoil Pls, repro steps

**Comment by dinkumoil** [comment]
@kvichans Please read my posting above. My lunch time is over, I have no time until the evening.

**Comment by kvichans** [comment]
> Docked FiL is visible and focus is into tab text -- Shift+Tab fails

No repro

**Comment by Alexey-T** [comment]
@kvichans Stable repro-- all tab contents hides in all tabs
video!
[Screencast 2019-12-10 18:18:05.zip](https://github.com/kvichans/cuda_ext/files/3945587/Screencast.2019-12-10.18.18.05.zip)

**Comment by Alexey-T** [comment]
And cudaext history
[plugin history.zip](https://github.com/kvichans/cuda_ext/files/3945615/plugin.history.zip)

**Comment by kvichans** [comment]
Yes, i see and have repro

**Comment by Alexey-T** [comment]
@dinkumoil Fixed in Cud. Wait for next update, plugin was ok.

**Comment by Alexey-T** [comment]
fixed?
