### ISSUE TITLE
Add commands "Move tab left" and "Move tab right"

### ISSUE THREAD

**Issue by dinkumoil** [kvichans/cuda_ext#141]
The commands should be able to change the order of tabs as they are displayed in the tab bar of their tab group. Users can then change tabs order by clicking menu entries or pressing keyboard shortcuts. Currently this can be done only by mouse drag&drop operation.

* Command `Move tab left` -> Move active tab to the left within tab bar of its tab group. If the tab was the leftmost tab it should become the rightmost tab.
* Command `Move tab right` -> Move active tab to the right within tab bar of its tab group. If the tab was the rightmost tab it should become the leftmost tab.

**Comment by kvichans** [comment]
ToDo

**Comment by dinkumoil** [comment]
Thank you, works great.
