### ISSUE TITLE
"Find in lines"- left search field don't work as needed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#143]
1)

- entred "req" in right field
- now I want to find as-i-type, i enter "exec" in left field
--> plugin still finds term "req" and not "exec"

2) opened another file. now entering "opt" in left field (plugin shows "req" in right field) DON'T find good- it finds "end" or "{$i" - crap

**Comment by Alexey-T** [comment]
![Screenshot from 2020-05-20 16-43-59](https://user-images.githubusercontent.com/4154978/82453372-1e86cf00-9ab9-11ea-851a-9eb59bede22f.png)

**Comment by Alexey-T** [comment]
@kvichans ?

**Comment by kvichans** [comment]
В работе

**Comment by Alexey-T** [comment]
forum user “tmsg” needs this command. You can ask him for anything

**Comment by kvichans** [comment]
Ясно

**Comment by kvichans** [comment]
Опубликовал.
Оказалось, что API выдает ошибочные сведения о контроле с фокусом, если форма в docked режиме. Удалось подобрать костыль.

**Comment by Alexey-T** [comment]
если что то я могу поправить. скажите. если это не баг Лаз. который портит.

**Comment by kvichans** [comment]
Поищу репро
