### ISSUE TITLE
lang str

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#145]
"to find: >2 signs in the left, ENTER for the right"
-- bad text.

->
"Left input: at least 3 chars needed. ENTER to search from right input"
shorter:
"Left input: at least 3 chars. ENTER to use right input"

@kvichans

**Comment by kvichans** [comment]
Все это не точно.
Нужно коротко пояснить, что `в левом достаточно ввести 3 символа или(!) нажимать [S]Ent, а в правом нужно нажимать [S]Ent`

**Comment by Alexey-T** [comment]
я поправил строки. что мне теперь поправить?

**Comment by kvichans** [comment]
Ок. Поставлю `Left input: at least 3 chars. Right input: ENTER.`
