### ISSUE TITLE
Find in lines, left input focused-- found text from right fld

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#146]
Enter: find next occur of LEFT field
Shift+Enter: find prev occur of LEFT field
if left is focused.

already done:
Enter, Shift+Enter: the same for right field. if right is focused.
@kvichans

**Comment by kvichans** [comment]
Не вижу. У меня:
- Если активно левое поле, то [Shift+]Enter отрабатывает по его содержимому
- Если активно правое поле, то [Shift+]Enter отрабатывает по его содержимому

Опишите детали вашего репро

**Comment by Alexey-T** [comment]
вот видео. ОК?
есть повтор под Лин?
[Screencast 2020-05-27 13:39:34.zip](https://github.com/kvichans/cuda_ext/files/4688192/Screencast.2020-05-27.13.39.34.zip)

**Comment by kvichans** [comment]
Версия последняя?
![image](https://user-images.githubusercontent.com/7419630/83020003-88aaf100-a030-11ea-95ca-ee639c9e41a8.png)

Так как описываете было в предыдущей

**Comment by Alexey-T** [comment]
да последняя
![Screenshot from 2020-05-27 15-55-11](https://user-images.githubusercontent.com/4154978/83021320-7f228880-a032-11ea-9c5b-7c850cfef06f.png)

**Comment by kvichans** [comment]
Есть репро. Оказалось опять заморочки док-моды. Ищу костыль или пример для ядра

**Comment by Alexey-T** [comment]
?
