### ISSUE TITLE
"Insert unicode char" dont support 1 or 3-digit hex code

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#147]
```
        hexcode = hexcode.upper()
        hexcode = hexcode[2:]   if hexcode.startswith('0X') else hexcode
        hexcode = '00'+hexcode  if len(hexcode)==2          else hexcode
```
2-digit is ok, 4 is ok, 1 or 3 is not

**Comment by kvichans** [comment]
Я в Юникоде профан.
Как нужно сделать?

**Comment by Alexey-T** [comment]
получили строку из dlg_input
если длина>4, ошибка
если <4, добиить нулями слева до 4

**Comment by Alexey-T** [comment]
вместо
        hexcode = '00'+hexcode  if len(hexcode)==2          else hexcode

**Comment by kvichans** [comment]
> вместо

Дальше не понятно

**Comment by Alexey-T** [comment]
даю Pull.
