### ISSUE TITLE
"Find in lines" - more options

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#148]
@kvichans 
http://synwrite.sourceforge.net/forums/viewtopic.php?p=13838#p13838

Maybe add an option to FIL - "Initially focus the left input field"?
Maybe add an option "Width of left input field", ".. of right input field"?

**Comment by kvichans** [comment]
1. Сейчас FiL запоминает последний использованный редактор для ввода. Кроме того есть команды `Alt+Left/Right` для перекидывания строк между редакторами. ИМХО опция не нужна.
2. Размеры редакторов - да, можно по resize вытягивать **оба** (сейчас только комбо - ToDo). Эти размеры сохраняются в док-режиме. Опция не нужна

Кроме того, если tmsg себе сделал форк и настроил под свои потребности, то какой смысл править общий FiL?

**Comment by Alexey-T** [comment]
ОК
