### ISSUE TITLE
User wants that CudaExt_py35 has new FindInLines code

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#150]
http://synwrite.sourceforge.net/forums/viewtopic.php?p=13859#p13859

**Comment by kvichans** [comment]
Перенес последний FiL в ext35, опубликовал

**Comment by Alexey-T** [comment]
@tmsg-gh CudaExt author added last FindInLines to Py 3.5 version. please test?

**Comment by tmsg-gh** [comment]
@kvichans: see http://synwrite.sourceforge.net/forums/viewtopic.php?p=13883#p13883

**Comment by kvichans** [comment]
![image](https://user-images.githubusercontent.com/7419630/83630752-05941880-a5a5-11ea-85e3-e0efc19ed713.png)
