### ISSUE TITLE
'Align in lines  to .... by margin' needs warning if margin is too big (2000 default)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#156]
...I got werid result with 1000's spaces - because dlg used margin value=2000.
show warning if margin is>200.

**Comment by kvichans** [comment]
Не понимаю, что и где не так. "2000" в CdExt не встречается.

**Comment by Alexey-T** [comment]
Плаг читает PROP_MARGIN - и это 2000. надо давать warning "Are you sure you want to use such margin value: 2000 ?"

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Я сделал чуть иначе - предложил задать нужный margin
![image](https://user-images.githubusercontent.com/7419630/84231644-41743400-aaf7-11ea-8c55-177d66810957.png)

**Comment by Alexey-T** [comment]
Use the margin to aliNG
->
Align by margin value:

**Comment by kvichans** [comment]
ok
