### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#16]
Rename- такое есть в син. мне это иногда надо но не хочется Пас-кодом делать. можно сделать? чтобы таб переоткрывался с новым именем после ренейма. (можно на том же месте в группе?)
(и желательно диалог ренейма как в Син.)

**Comment by kvichans** [comment]
todo

**Comment by kvichans** [comment]
Как из плагина при закрытии измененного файла остановиться, если пользователь не хочет ни сохранять, ни терять изменения?

1. Сейчас команда ed.cmd(cmd_FileClose) задает пользователю вопрос, но похоже нет возможности узнать, что файл остался открытым - всегда возвращается None. Более того, возврат происходит **до ответа** пользователя.
2. Может быть можно как-то узнать про наличие *изменений*? Тогда плагин сам задаст вопрос пользователю.

**Comment by Alexey-T** [comment]
я пока понял п.2.- Можно, есть  get_prop(PROP_MODIFIED)

**Comment by kvichans** [comment]
Упс.
- Плагин узнал, что текст изменен. 
- Спросил пользователя "Сохранять? Да/Нет/Отмена". Получил ответ "Нет", значит сохранять не нужно.

Какой командой плагин сможет закрыть файл без сохранения изменений?

**Comment by Alexey-T** [comment]
тут надо или 1) дать установку prop_modified (to false)
или 2)дать команду cmd_FileCloseNoAsk

**Comment by kvichans** [comment]
ОК. Оба способа не были мне известны.

**Comment by kvichans** [comment]
cmd_FileCloseNoAsk это что-то новое? у меня в API его нет
или пишется по-другому?

**Comment by Alexey-T** [comment]
эти способы не сделаны-Что лучше? лучше 1- потому что можно закрыть все табы без сейва?

**Comment by kvichans** [comment]
а-а-а, "тут надо" это не мне надо использовать, а вам надо сделать...
Тогда лучше пойти третьим путем!
Ввести глобальное свойство Куд: можно_задавать_вопросы
В объектной модели MS Office это bool-свойство App.DisplayAlerts. Я им очень часто пользуюсь. Когда App.DisplayAlerts выключено, приложение само принимает решения вместо того, чтобы спрашивать

**Comment by Alexey-T** [comment]
Но 3путь значит что НЕЛЗЯ поставить алерт для одного таба. А путь set_prop(PROP_MODIFIED, '0') лучше. можно ставить алерт как хошь
Сделал это

**Comment by Alexey-T** [comment]
Бт через 10мин

**Comment by kvichans** [comment]
Глоб.свойство - это очень удобно! 
- Можно перед большим кодом выключить его и быть уверенным, что пользователя не будут дергать
- Можно делать пакетные обработки большого числа файлов, не волнуясь, что бесконечно придется отвечать на вопросы

**Comment by Alexey-T** [comment]
Подумаю,надо ли оно *тут? тут не надо

**Comment by kvichans** [comment]
бета кривая - все json-ы открылись с ошибками

**Comment by kvichans** [comment]
взял предыдущий default.json и cudatext.exe - открылось нормально

**Comment by Alexey-T** [comment]
Там в либе json теперь требует чтобы не было , перед } 
(почему так сделали?)

**Comment by kvichans** [comment]
да уж!

**Comment by Alexey-T** [comment]
запостил http://mantis.freepascal.org/view.php?id=29718

**Comment by kvichans** [comment]
я конечно справлюсь - но остальным это подстава!
вам нужно предобрабатывать json - делать замены `,(\s*})` на `\1` перед загрузкой в Куд

**Comment by Alexey-T** [comment]
если я узнаю как воткнуть это в fcl-json

**Comment by kvichans** [comment]
Еще беда: default.json не загружается в питон
`Invalid control character at: line 466 column 30 (char 5552)`
Из этой строки извлеклось только
`"links_regex": "\\b(https?:`

**Comment by kvichans** [comment]
перед загрузкой в питон удаляю все комментарии

**Comment by Alexey-T** [comment]
А тут символы // в строке

**Comment by kvichans** [comment]
а-а!

**Comment by kvichans** [comment]
Проблема. Похоже опять на фокусы многопоточности.
Вот две строки из плагина
```
        ed.cmd(cmd_FileClose)
        file_open(new_path, group)
```
Если последнюю убрать, то первая нормально закрывает файл.
Если последняя есть, то старый файл остается открытым и открывается новый

**Comment by Alexey-T** [comment]
причина- fileclose выполняется не сразу. делается таймер. он работает. пауза тут.. 150мс

надо делать паузу http://stackoverflow.com/questions/510348/how-can-i-make-a-time-delay-in-python

**Comment by kvichans** [comment]
Грязный хак. Если нет других способов, то оставлю
`time.sleep(0.3)`

**Comment by kvichans** [comment]
Нужно в вики перечислить команды, результата которых нужно ждать.

**Comment by kvichans** [comment]
Упс. Не помогло.
```
        ed.cmd(cmds.cmd_FileClose)
        time.sleep(0.3)
```

**Comment by Alexey-T** [comment]
А так?

        ed.cmd(cmds.cmd_FileClose)
        time.sleep(0.35)
        msg_status('')

**Comment by kvichans** [comment]
что из этого должно помочь? 
 - 0.3 ==> 0.35?
- msg_status?

Это похоже на слепой поиск

**Comment by kvichans** [comment]
Три раза сработало. Есть ли уверенность, что **всегда** будет работать?

**Comment by Alexey-T** [comment]
~~~
class Command:
    def run(self):
        s = ed.get_filename()
        ed.cmd(cmd_FileClose)
        time.sleep(0.3)
        msg_status('')
        file_open('/home/user/aa.md')
        ~~~

**Comment by kvichans** [comment]
?

**Comment by Alexey-T** [comment]
0.3 это Ок. А msgstatus дает обработку таймера

**Comment by kvichans** [comment]
что такое *обработка таймера*?

**Comment by Alexey-T** [comment]
таймер запущен по cmd_fileclose. Он реально выполнится если Куд имеет активность.Она есть при msg_status

**Comment by kvichans** [comment]
это за пределами моего понимания.
это дает уверенность, что будет всегда закрываться?

**Comment by Alexey-T** [comment]
Думаю да

**Comment by kvichans** [comment]
Какие еще команды нужно завершать такой магией?

**Comment by Alexey-T** [comment]
исходник- proc_cmd.pas- function IsCommandNeedTimer

**Comment by kvichans** [comment]
Если я правильно читаю Паскаль (это мне сложно), то видимо этот список
```
    cmd_FileNew               ,
    cmd_FileOpen              ,
    cmd_FileReopen            ,
    cmd_FileExit              ,
    cmd_FileClose             ,
    cmd_FileCloseOtherThis    ,
    cmd_FileCloseOtherAll     ,
    cmd_FileCloseAll          ,
    cmd_FileCloseAndDelete    ,
    cmd_FileExportHtml        ,

    cmd_OpsClearRecent        ,
    cmd_OpsOpenDefault        ,
    cmd_OpsOpenUser           ,
    cmd_OpsOpenLexerOvr       ,
    cmd_OpsOpenFileTypes      ,
    cmd_OpsFontText           ,
    cmd_OpsFontUi             ,
    cmd_DialogSaveTabs        ,
    cmd_ToggleFullScreen      ,
    cmd_OpsReloadAndApply     ,
    cmd_DialogLexerProp       ,
    cmd_DialogLexerLib        ,
    cmd_DialogColors          ,
    cmd_ToggleSidePanel       ,
    cmd_ToggleBottomPanel     ,
    //cmd_ShowPanelConsole      ,
    //cmd_ShowPanelOutput       ,
    //cmd_ShowPanelValidate     ,
    cmd_ToggleFindDialog      ,
    cmd_DialogLoadLexerStyles,
    cmd_ToggleToolbar       ,
    cmd_ToggleStatusbar     ,
    cmd_ResetPythonPlugins  ,
    cmd_DialogCharMap       ,
    cmd_RunLastCommandPlugin ,

    cmd_DialogGotoBookmark,
    cmd_DialogCommands   ,

    cmd_SplitTabToggle    ,
    cmd_SplitTabHorzVert  ,
    cmd_SplitTab3070      ,
    cmd_SplitTab4060      ,
    cmd_SplitTab5050      ,
    cmd_SplitTab6040      ,
    cmd_SplitTab7030      ,

    cmd_Groups1      ,
    cmd_Groups2horz  ,
    cmd_Groups2vert  ,
    cmd_Groups3horz  ,
    cmd_Groups3vert  ,
    cmd_Groups3plus  ,
    cmd_Groups3plushorz  ,
    cmd_Groups4horz  ,
    cmd_Groups4vert  ,
    cmd_Groups4grid  ,
    cmd_Groups6grid  ,

    cmd_GroupActivateNext ,
    cmd_GroupActivatePrev ,

    cmd_MoveTabToGroupNext ,
    cmd_MoveTabToGroupPrev ,

    cmd_MenuEnc           ,
    cmd_MenuEnds          ,
    cmd_MenuLexers        ,

    cmd_AutoComplete      ,
    cmd_GotoDefinition    ,

    cmd_HelpAbout     ,
    cmd_HelpForum     ,
    cmd_HelpWiki      ,
    cmd_HelpMouse     ,
    cmd_HelpChangelog ,
    cmd_HelpLexers    :
```

**Comment by Alexey-T** [comment]
да..

**Comment by kvichans** [comment]
Я готов в cudax_lib сделать обертку для ed.cmd, которая будет по этому списку решать ставить задержку или нет.
Вызов `time.sleep(0.3);app.msg_status('')` всегда достаточен? 

Почему все это нельзя сделать в ядре?

**Comment by Alexey-T** [comment]
попробую сделать сам в ed.cmd

**Comment by Alexey-T** [comment]
Bt

**Comment by kvichans** [comment]
Норм

**Comment by kvichans** [comment]
готово
попробуйте переименование
еще можете попробовать открывать рядом с тек.вкладкой и перемещения тек.вкладки

**Comment by Alexey-T** [comment]
Попробую..

**Comment by Alexey-T** [comment]
Cancel-- ренеймит

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
Проверил, работает, ок
правка языка-

DONT_NEED_CHANGE    = "Text change not needed"
 "It is existed directory\n{}\n\nChoose another name." --- "Directory already exists: ..........."

**Comment by kvichans** [comment]
спасибо
