### ISSUE TITLE
i18n missed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#160]
There are some gettext parentheses missing:

In cd_ext.py:
line 1335: return app.msg_status('Need selection')
line 1359: app.dlg_input('Enter string to fill selection', '')

In cd_ext_find_repl.py:
line 972: return app.msg_status('Not digit margin')

**Comment by kvichans** [comment]
Спасибо

**Comment by Alexey-T** [comment]
fixed?

**Comment by kvichans** [comment]
да
