### ISSUE TITLE
VSCode now has such new commands

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#161]
![image](https://user-images.githubusercontent.com/4154978/85638045-8ec2da80-b68d-11ea-9bce-d6c4a9572265.png)

**Comment by kvichans** [comment]
Не понял идею. Можете пояснить?

**Comment by kvichans** [comment]
Верно ли что это похоже на Shift+Click, который выделяет от каретки до места клика?
Где и как можно отображать наличие/положение якоря, чтобы пользователь это мог видеть?

**Comment by Alexey-T** [comment]
не очень похоже.
ставить ed.attr в один символ.

**Comment by kvichans** [comment]
Туча вопросов
- Якорь либо один, либо не одного? То есть постановка нового уничтожает старый (если был)?
- Как найти якорь в тексте? Например, ушел далеко от него.
- Как долго живет якорь? Если его поставили и забыли, то при каких действиях он сам исчезает?

**Comment by Alexey-T** [comment]
- не знаю, не ставил новый VS- пусть один
- плагину найти? юзеру? юзеру- по марке в micromap- ed.attr вроде могет
- надо тестить в VS

**Comment by Alexey-T** [comment]
Можно так- при делании якоря, подпишитесь на on_change- при событии удалите як.
и на on_caret- при событии когда ЕСТЬ выделение- удалите як

**Comment by kvichans** [comment]
Про случай с несколькими каретками. "Установить якорь" можно - поставить в местах каждой из кареток. Но у команды "Протянуть от якоря до каретки" появляется неоднозначность - какую каретку с каким якорем соединять. Видимо якорь только один. Итого: много кареток - отказ.

**Comment by Alexey-T** [comment]
да. Команды не подходят к кареткам - у них цель дать выделение клавой

**Comment by Alexey-T** [comment]
давайте отменим это. Не надо перегружать Ext обработкой ивентов. Это должен быть новый плагин
