### ISSUE TITLE
docs for BatchReplaces

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#163]
положите это в папку readme или где-то там. можете и из диалогов показать.
 
[_rep_d.zip](https://github.com/kvichans/cuda_ext/files/4864089/_rep_d.zip)

**Comment by kvichans** [comment]
1. Положить в readme могу. Только не понимаю, что это даст пользователю. Каким путем он найдет этот обзор?
2. Из диалога показать хотелось бы. Осталось придумать способ. Дать ссылку на локальный файл?

**Comment by kvichans** [comment]
Сделал через `os.system()`
![image](https://user-images.githubusercontent.com/7419630/86436531-1b633d80-bd0b-11ea-9cd2-c8354355f950.png)

Но при переносе из ГХ потерялись стили и тексты.
Может быть знаете способ, как получить конечный html из вики в ГХ?

**Comment by Alexey-T** [comment]
>как получить конечный html из вики в ГХ?

оно в markdown?
плагин- Markdown Preview- дает html.

**Comment by kvichans** [comment]
Мне понравилась идея делать html-гайды для плагинов. Пока нет контрола для их просмотра внутри Куд, можно выкидывать в браузер.
Markdown Preview изучу при создании следующего гайда.

**Comment by Alexey-T** [comment]
>        if tag=='guid':     return (os.system(os.path.dirname(__file__)+os.sep+'readme/batch_replacements.html'), [])[1]

не работает в Лин.
погуглите как открыть html(не знаю как)

**Comment by Alexey-T** [comment]
https://www.pythonforbeginners.com/code-snippets-source-code/python-webbrowser/

**Comment by kvichans** [comment]
Питон библиотека не исчерпаема :)
Узнал про `webbrowser`. Спасибо

**Comment by kvichans** [comment]
Пробуйте из ГХ

**Comment by Alexey-T** [comment]
Ок. можно публ.

**Comment by Alexey-T** [comment]
import webbrowser -лучше на месте- где открываете html

**Comment by kvichans** [comment]
Опубликовал

**Comment by Alexey-T** [comment]
brawser -> browser !

**Comment by Alexey-T** [comment]
1.7.20 (2020-07-03) -> 1.7.21

**Comment by kvichans** [comment]
поправлю
