### ISSUE TITLE
need more space between inputs

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#167]
FIF is ok
![Screenshot from 2020-07-04 23-56-56](https://user-images.githubusercontent.com/4154978/86520890-37252b80-be52-11ea-845f-68f22484a832.png)

RepInLines not
![Screenshot from 2020-07-04 23-57-33](https://user-images.githubusercontent.com/4154978/86520891-3ee4d000-be52-11ea-832a-d8585485418c.png)

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Попробуйте из ГХ
