### ISSUE TITLE
menu monospaced font

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#170]
бетка 1.107.2 будет имметь опцию в dlg_menu:

* MENU_EDITORFONT: Use editor's font (monospaced) for list items, instead of variable-width UI font.

это полезно для CudaExt для менюхи которая показывает дерево из codetree.

**Comment by kvichans** [comment]
Да, жду

**Comment by Alexey-T** [comment]
Released - 1.107.5

**Comment by kvichans** [comment]
Внедрю в свои плаги

**Comment by kvichans** [comment]
Хорошо стало :)
![image](https://user-images.githubusercontent.com/7419630/88183024-99936f80-cc39-11ea-9ab4-31098872c2e9.png)

**Comment by kvichans** [comment]
И Дерево стало выглядеть лучше
![image](https://user-images.githubusercontent.com/7419630/88188709-e3cc1f00-cc40-11ea-9a6f-146b2bc5c368.png)

**Comment by kvichans** [comment]
@Alexey-T 
При использовании `dlg_nemu(MENU_LIST_ALT+MENU_EDITORFONT, ...)` 
![image](https://user-images.githubusercontent.com/7419630/88191124-c2b8fd80-cc43-11ea-9fb0-663593d61d80.png)

Минимальный Репро
`dlg_menu(MENU_LIST_ALT+MENU_EDITORFONT, ['ala\t11', 'bwb\t22'])`

**Comment by Alexey-T** [comment]
Спасибо. :( to fix

**Comment by Alexey-T** [comment]
поправил.
