### ISSUE TITLE
codetree in menu: too big dlg

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#171]
меню вот какое- не умещается. почему? как сделать ОК высоту?
![Screenshot from 2020-08-24 16-32-34](https://user-images.githubusercontent.com/4154978/91050615-9409ba80-e627-11ea-8f15-cde2ee180daf.png)

**Comment by kvichans** [comment]
Да, те же ножницы, что и `Show Usages` - нужен конфигуратор.

Сейчас можно руками задать в `plugin history.json`:
- Найти/создать корневой ключ `"cd_ext_tree":{...}`
- В нем создать ключ:значение в виде `"symbols.h":600,`

**Comment by Alexey-T** [comment]
нет, так нельзя. =(
дайте нормальный дефолт плз.

**Comment by kvichans** [comment]
Нормальный это сколько?

**Comment by Alexey-T** [comment]
800x600 это стд разрешение для старых моников.

**Comment by kvichans** [comment]
это же не значение для умолчания
столько делать?

**Comment by Alexey-T** [comment]
550.

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Будет в след. обновлении - само слишком мелко
