### ISSUE TITLE
Find tab by title - UI

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#174]
Кмд subj не находит титул Untitled4 по строке `unti`

**Comment by Alexey-T** [comment]
А почему вообще не дать тут dlg_menu с фильтром??? это сразу будет видно что нашли 3 таба на данный титул, видно какие.

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
fixed in pull-req.
