### ISSUE TITLE
Symbols list- 306:306

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#176]
Почему два числа повторены в прав.колонке?
![Screenshot from 2020-09-17 17-16-34](https://user-images.githubusercontent.com/4154978/93483633-af57a500-f909-11ea-9f59-8e784344c398.png)

**Comment by kvichans** [comment]
<строка от> : <строка до>

**Comment by kvichans** [comment]
![image](https://user-images.githubusercontent.com/7419630/93484549-b4692400-f90a-11ea-8ce0-428199746c8d.png)

**Comment by Alexey-T** [comment]
для однострочных зачем нам 2 числа? они путают.

**Comment by kvichans** [comment]
Это спорно. Когда рядом стоят много диапазонов, но УДОБНЕЕ читать по первым числам - они друг под другом

**Comment by kvichans** [comment]
Кстати, нужно будет доделать - чтобы все были с одинаковым кол-вом разрядов.

**Comment by Alexey-T** [comment]
это вот это https://www.w3schools.com/python/trypython.asp?filename=demo_ref_string_ljust2
