### ISSUE TITLE
Paste and Indent command

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#18]
такая команда есть в Лазарус+Сублиме. Она вставляет блок и подстраивает его строки чтобы был нормальный indent- чтобы стыковалось с кодом до вставки
(учитывает инденты строк до блока и инденты строк блока) 

 описание https://t.co/5SJDmx0RJK

**Comment by kvichans** [comment]
Если я правильно понял, нужно перед вставкой фрагмента дополнить начала строк подходящими пробелами/табами. Так?

**Comment by Alexey-T** [comment]
иногда удалить лишние пробелы.

**Comment by kvichans** [comment]
мне нравиться
todo

**Comment by kvichans** [comment]
Готово
Много разных случаев, может быть не все учел. Попробуйте

**Comment by Alexey-T** [comment]
не хор. Делаем в паскаль блок выделение

~~~
  TForm1 = class(TForm)
    ToolBar1: TToolBar;
    ToolButton1: TToolButton;
    ToolButton2: TToolButton;
  private
    { private declarations }
  public
    { public declarations }
  end;
~~~

делаем с индентом 4 пробела 
~~~
    begin
    end;
~~~

делаем Паст в колонке 1 перед end.
нужно чтобы было
~~~
    begin
      TForm1 = class(TForm)
        ToolBar1: TToolBar;
        ToolButton1: TToolButton;
        ToolButton2: TToolButton;
      private
        { private declarations }
      public
        { public declarations }
      end;
    end;
~~~

 то же д.быть при Пасте в любой колонке перед 'end'

**Comment by kvichans** [comment]
Не понял. 
Сейчас плагин повторяет сдвиг той строки на которой стоит каретка. 
А какая еще может быть логика?

**Comment by Alexey-T** [comment]
Еще прибавить индент (смотря по опции едитора, таб или проб.)

**Comment by Alexey-T** [comment]
прибавить индент надо НЕ всегда. если мы пасстим после begin или { надо. иначе не надо

**Comment by kvichans** [comment]
А как плагин узнает **когда** надо прибавлять?

**Comment by Alexey-T** [comment]
если перед Пастой есть слово begin или { ,для 90% лексов ок

**Comment by kvichans** [comment]
Поясните про Паскаль (На С-подобных я программировал): после begin может быть любое число пробельных в строке?

**Comment by Alexey-T** [comment]
да, пробелы-табы-концы в Пас не значат

**Comment by kvichans** [comment]
todo

**Comment by kvichans** [comment]
fix
Вставка "над текущей" всегда использует сдвиг этой строки.
Вставка "под текущей" происходит с доп.сдвигом, если строка заканчивается на
- `begin` (в любом регистре)
- `{`
- `:`
- `then` (в любом регистре)

**Comment by Alexey-T** [comment]
еще не полн. ОК, если есть такая строка-

        if (i=High(DBCSToUTF8)) or (j=MaxGapSize) then begin 

и ставить каретку после begin (та же строка) и делать Паст, то пастится выше строки, а надо ниже

**Comment by kvichans** [comment]
А какую из команд двух добавленных вы вызываете?

**Comment by Alexey-T** [comment]
а, тогда Ок
Вот недочет,

  RangeIsString:=false;
  for i:=1 to length(s) do begin

каретка в нач. стр. с for. Делаю paste below. Нужно вставка в позиции катетки, а делается ниже строки с for

**Comment by kvichans** [comment]
Так и вызывайте команду `paste_with_indent_above`

**Comment by Alexey-T** [comment]
Если я сделаю хоткей на paste_below, то он тут не сработает, плохо, Паст надо всегда в позиции каретки

**Comment by kvichans** [comment]
Не получится иметь **одну** команду.

**Comment by Alexey-T** [comment]
почему, в Лазарус одна Паста

**Comment by kvichans** [comment]
Расскажите подробно как *она* работает

**Comment by kvichans** [comment]
Как ЛазПаста решает до или после тек.строки вставлять?

**Comment by Alexey-T** [comment]
блок пастится в поз каретки. если я пастю в нач строки или после пробелов (каретка не после текста) то индент блока подстр-ся под индент верхней стр.

**Comment by kvichans** [comment]
не понятно
что означает 
>в поз каретки

?

**Comment by Alexey-T** [comment]
Можете скачать попробовать L?

**Comment by kvichans** [comment]
нет уж

**Comment by kvichans** [comment]
жабер?
