### ISSUE TITLE
Some menus need the fixed font?

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#184]
@miroslavmatas
Subj was the request from you? can you remember that request, what was asked here?

**Comment by MiroslavMatas** [comment]
yes, but opposite - CudaExt, Open Recent File menu - that list is currently realized via fixed font, and I request the same like for Command Palette, or for Go To File (Project Manager), or Command history (latest plugin…)

**Comment by Alexey-T** [comment]
So do you want this:

- make font NOT-fixed in 'CudaExt - Open recent file'
or
- make font fixed - in the mentioned Cud's dialogs ?

**Comment by MiroslavMatas** [comment]
please - _**make font NOT-fixed in 'CudaExt - Open recent file'**_

**Comment by kvichans** [comment]
@MiroslavMatas 
Try new version `cuda_ext`
See History
```
1.7.34 (2021-08-23)
added: New options for user.json: 
    "cuda_ext.<command>.menu.<style>": <value>
where 
    command is one of (recents, tabs_bookmark, tab_bookmark, layouts, tree_symbols) 
and
    style is one of (monofont, no_fuzzy, centered)
Set value to 0 or false to switch style off
Set value to 1 or true to switch style on
```
To set not-fixed font in `Open recent file` add to `user.json` that line
`"cuda_ext.recents.menu.monofont":false,`

**Comment by MiroslavMatas** [comment]
works as designed!
thanks a lot…
