### ISSUE TITLE
patch from forum user: "Align by carets" cmd added

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#185]
[pch.zip](https://github.com/kvichans/cuda_ext/files/7108526/pch.zip)

 Описание- новая команда, выравнивает пробелами позиции всех кареток.
еще добавить в history надо. @kvichans

**Comment by Alexey-T** [comment]
```
for i in reversed(range(len(carets))):
  if (i>0) and (carets[i][1]==carets[i-1][1]):
    del carets[i]
```
- удаление кареток на одной строке.

**Comment by Alexey-T** [comment]
Вот поправленая версия
[cd_ext_find_repl.zip](https://github.com/kvichans/cuda_ext/files/7117308/cd_ext_find_repl.zip)

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Как по-английски будет описание этой команды в меню?

**Comment by Alexey-T** [comment]
Align carets by spaces - Aligns positions of multi-carets by inserting space-chars, so all carets go to the same column

**Comment by kvichans** [comment]
Опубликовал (только последнюю предложенную фразу увидел поздно, она будет в Истории позже)
