### ISSUE TITLE
Commd "Go to next tab in all groups"/"Go to prev...."

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#2]
http://forum.wincmd.ru/viewtopic.php?p=113980#113980
команда как Ctrl+Tab но **по всем группам сразу

**Comment by kvichans** [comment]
Какой тип у вашего поста? 
 - пожелание
 - претензия
 - todo для себя

**Comment by Alexey-T** [comment]
Wish для поль-ля wincmd.ru

**Comment by kvichans** [comment]
Не понял *идею*. Кто и чем может помочь пользователю wincmd.ru?

**Comment by kvichans** [comment]
Догадка: плагин-команда, которая будет переключать **все** вкладки по циклу. Да?

**Comment by Alexey-T** [comment]
да
Вы можете помочь:)
Все табы по циклу вперед+назад

**Comment by kvichans** [comment]
да, скоро будет в cuda_ext

**Comment by kvichans** [comment]
выложил

**Comment by Alexey-T** [comment]
Не переходит их гр1 в гр3

и еще пауза почти 1с при переходе((

![tab](https://cloud.githubusercontent.com/assets/4154978/11430179/cbeecd72-9493-11e5-96bd-160b72b01636.png)

**Comment by kvichans** [comment]
да, такой случай упустил :)
оптимизацию придумаю

**Comment by Alexey-T** [comment]
Вы там вызываете попытку перейти, одну еще одну...  лучше просто перебрать ed_handles

**Comment by Alexey-T** [comment]
можно так.
ставите у ed PROP_TAG='test'
перебираете все хендлы пока не найдете редактор с PROP_TAG='test'
дальше понятно.
убираете PROP_TAG.

**Comment by kvichans** [comment]
Выложил обновление кода и Release
