### ISSUE TITLE
All Bookmarks from Project…

### ISSUE THREAD

**Issue by MiroslavMatas** [kvichans/cuda_ext#211]
will be possible to add new feature/dialog? - Bookmark list for all project files…

so I will be able to open file from project what is not at current session (not already open) and go to mentioned bookmark

thanks in advance

![image](https://user-images.githubusercontent.com/42316770/224261371-25678b7c-5e2c-4528-817e-8e5d0e806c0a.png)

**Comment by Alexey-T** [comment]
Maybe it';s better to implement via plugin? Not pascal code? seems yes. speed is not of concern.

**Comment by MiroslavMatas** [comment]
> Maybe it';s better to implement via plugin? Not pascal code? seems yes. speed is not of concern.

correct, speed is not priority here
