### ISSUE TITLE
cuda_ext + rclone?

### ISSUE THREAD

**Issue by ghost** [kvichans/cuda_ext#223]

**Comment by Alexey-T** [comment]
CudaExt don't have custom context menu. user can use Configure_Menu plugin to customize the context menu.

**Comment by Alexey-T** [comment]
Docs:
https://wiki.freepascal.org/CudaText_plugins#Configure_Menu

> How do I configure a custom menu to call a function on a command line?

1. install Configure_Menu, run its dialog, create the file menu.json and check the dialog option to load menu.json on start.
2. install External_Tools plugin, create the tool to run e.g. rclone
3. in menu.json, add line to call Ext_Tools tool (made in step 2). screenshot in the https://wiki.freepascal.org/CudaText_plugins#Configure_Menu shows the example line which calls some Ext_Tools tool.
