### ISSUE TITLE
'Re-wrap lines' dialog: dlg size is decreased each time

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#224]
отзыв с форума не мой:
https://synwrite.sourceforge.net/forums/viewtopic.php?p=19286#p19286

повторил в linux x64 qt5 версии 1.214.7.2.

размеры в 'plugin history.json' уменьшаются с каждым вызовом:
```
{
  "cd_kv_dlg": {
    "Re-wrap lines": {
      "x": 369,
      "y": 627,
      "w": 603,
      "h": 24
    }
  }
}
```

тут уже высора 24, что дает невидимый диалог.

вызов диалога - в cd_ext_find_repl.py
```
   ag  = DlgAg(form=d(cap=_('Re-wrap lines')       ,w=5+165+5, h=5+120+5)
               ,ctrls=[0
        ,('mar_',d(tp='labl',tid='marg' ,x=5        ,w=110  ,cap=_('&Margin:')      )) # &m
        ,('marg',d(tp='edit',y=5        ,x=5+105    ,w=60                           )) # 
        ,('csg_',d(tp='labl',tid='csgn' ,x=5        ,w=110  ,cap=_('&Comment sign:'))) # &c
        ,('csgn',d(tp='edit',y=5+30     ,x=5+105    ,w=60                           ))
        ,('svbl',d(tp='chck',y=5+60     ,x=5        ,w=165  ,cap=_('&Keep indent')  )) # &s
        ,('okok',d(tp='bttn',y=5+120-28 ,x=5        ,w=80   ,cap=_('OK'), def_bt='1',on=CB_HIDE)) #
        ,('cncl',d(tp='bttn',y=5+120-28 ,x=5+80+5   ,w=80   ,cap=_('Cancel')        ,on=CB_HIDE))
               ][1:]
               ,vals=d(marg=str(margin)
                      ,csgn=cmt_sgn
                      ,svbl=True)
               ,fid='marg'
        )
    aid,vals    = ag.show()
    if aid!='okok': return 
```

~~видимо причина в том что я пересобрал лазарус с НЕпримененным патчем: doc/qt5-fixes.patch~~

~~значит виноват лазарус.~~ но плагин тоже виноват. почему он сохраняет размеры диалога rewrap-lines? это диалог БЕЗ ресайза. его позицию и размеры НЕ надо сохранять.
уберите сохранение, плиз.

**Comment by Alexey-T** [comment]
повтор есть в gtk2-версии, видимо это не забытый патч виноват, а что-то еще.

повтор есть и с другими окнами CudaExt:
- Set carets aligned as column... - тут вообще плохо, диалог САМ закрывается (gtk2 linux)

**Comment by Alexey-T** [comment]
нашел временное решение-
в py/cuda_ext/cd_kv_dlg.py
найти
`def _form_acts`
и первым оператором сделать такой
```
def _form_acts(act, fprs=None, did=None, key4store=None):
    """ Save/Restore pos of form """
    return fprs
```

**Comment by kvichans** [comment]
Ого! Это явно избыточно и опасно - пострадают остальные.
Идея не хранить размеры, если форма не resizable, мне нравится. Попробую подобрать патч

**Comment by kvichans** [comment]
Патч
Заменить
```python
def _form_acts(act, fprs=None, did=None, key4store=None):
    ...
    elif act=='save' and did:
        for (k,v) in {k:v for k,v in fprs.items() if k in ('x','y','w','h')}.items():
            set_hist([fm_key, k], v)
```
на 
```python
def _form_acts(act, fprs=None, did=None, key4store=None):
    ...
    elif act=='save' and did:
        keys = ('x','y','w','h') if ('resize' in fprs or 'resize' in fprs.get('frame')) else ('x','y')
        for (k,v) in {k:v for k,v in fprs.items() if k in keys}.items():
            set_hist([fm_key, k], v)
```

Не тестировал.

**Comment by Alexey-T** [comment]
патч помог.

а почему форма восстанавливала w/h ? - там же у вас есть проверка на resize. может вы не учли то что ключ resize уже был удален из АПИ?

1.0.416 (app 1.157.2)
* deleted deprecated: "resize" property of forms in dlg_proc()

**Comment by kvichans** [comment]
Ну да - может быть.

**Comment by Alexey-T** [comment]
но как быть тем у кого уже запорчен plugins history?

**Comment by Alexey-T** [comment]
и потом если 'resize' удален, то новый патч повлияет на ВСЕХ, что не хорошо.

**Comment by kvichans** [comment]
> вместо resize надо юзать вот это--
> 
> * "border": int: Border-style of form, one of DBORDER_nnn constants.
>   ** DBORDER_NONE: No visible border, not resizable
>   ** DBORDER_SIZE: Standard resizable border (on Windows: with Minimize/Maximize buttons)
>   ** DBORDER_SINGLE: Single-line border, not resizable (on Windows: form has icon and Minimize button)
>   ** DBORDER_DIALOG: Standard dialog box border, not resizable (on Windows: form has no icon nor Minimize button)
>   ** DBORDER_TOOL: Like DBORDER_SINGLE but with a smaller caption
>   ** DBORDER_TOOLSIZE: Like DBORDER_SIZE but with a smaller caption

Он так и делает
```python
        elif 'resize' in fpr['frame'] and ('full-cap' in fpr['frame'] or 'min-max' in fpr['frame']):
            fpr['border']   = app.DBORDER_SIZE
        elif 'resize' in fpr['frame']:
            fpr['border']   = app.DBORDER_TOOLSIZE
```

**Comment by kvichans** [comment]
> и потом если 'resize' удален, то новый патч повлияет на ВСЕХ, что не хорошо.

`resize` не Куда, а плага. Не нужно паники

**Comment by kvichans** [comment]
> но как быть тем у кого уже запорчен plugins history?

Думаю...

**Comment by kvichans** [comment]
> но как быть тем у кого уже запорчен plugins history?

Уже была попытка эту ситуацию рулить
```python
def _form_acts(act, fprs=None, did=None, key4store=None):
    ...
    elif act=='move' and fprs:
        prev    = get_hist(fm_key)
        pass;                  #log__('prev={}',(prev)      ,__=(log4fun,)) if _log4mod>=0 else 0
        if not prev:    return fprs
#       if not fprs.get('resize', False):
        if 'resize' not in fprs.get('frame', ''):
            prev.pop('w', None)
            prev.pop('h', None)
        fprs.update(prev)
```
Можно попробовать вернуть проверку из комметария и объединить с живой проверкой. 
То есть заменить на 
```python
def _form_acts(act, fprs=None, did=None, key4store=None):
    ...
    elif act=='move' and fprs:
        prev    = get_hist(fm_key)
        pass;                  #log__('prev={}',(prev)      ,__=(log4fun,)) if _log4mod>=0 else 0
        if not prev:    return fprs
        if not fprs.get('resize', False) and 'resize' not in fprs.get('frame', ''):
            prev.pop('w', None)
            prev.pop('h', None)
        fprs.update(prev)
```

**Comment by Alexey-T** [comment]
не помогло. и предыдущий фикс для 'save' не помог - я забыл убрать мой фикс перед применением вашего фикса. пока ничего не помогло.

**Comment by Alexey-T** [comment]
применил мой тупой фикс.
