### ISSUE TITLE
ver 1.2.3 Dlg Favorites

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#28]
As SynWrite
![fav](https://cloud.githubusercontent.com/assets/7419630/15576811/63bc159e-2362-11e6-8567-8d5c66437683.JPG)

For importing Fav from SynWrite: 
- click "Add..." 
- select your "SynFav.ini" (see in "SynWrite\Settings").

**Comment by Alexey-T** [comment]
Ops, wanted Favor dialog and I missed post
Sorry
Will try it, tkx

**Comment by Alexey-T** [comment]
Better have separate Favorites plugin.

**Comment by kvichans** [comment]
ОК

**Comment by Alexey-T** [comment]
Separate plugin is **visible**. CudaEx item NOT visible.

**Comment by kvichans** [comment]
"Ppl" ? 
Уже делаю отдельный плаг

**Comment by Alexey-T** [comment]
ppl=people.

**Comment by Alexey-T** [comment]
Нужно чтобы код "ложился и на Син"..

**Comment by kvichans** [comment]
Посмотрю, что можно сделать

**Comment by kvichans** [comment]
Опубликовал https://github.com/kvichans/cuda_favorites

**Comment by kvichans** [comment]
Запустил этот диалог в Син. Что дальше?

**Comment by kvichans** [comment]
Сначала было нормально. Только галка не ставилась.  А потом стало так
![dlg-fav](https://cloud.githubusercontent.com/assets/7419630/16202214/6766387c-371d-11e6-8514-bd12bcf14a89.JPG)

**Comment by Alexey-T** [comment]
стало, из-за чего? Alt press? "act=1" видимо не раб-т?

**Comment by Alexey-T** [comment]
(wish: удалить код Favorits)

**Comment by kvichans** [comment]
(не понял что/где удалить)

**Comment by kvichans** [comment]
Обубликовал: https://github.com/kvichans/synw_favorites

**Comment by Alexey-T** [comment]
Удалить код Favorites in CudaExt.

**Comment by kvichans** [comment]
закомментировал, выложил
