### ISSUE TITLE
Open file from select

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#3]
есть файл в котором каретка на имени main.css
~~~
<link href="main.css" rel="stylesheet" type="text/css">
</head>
~~~
можно сделать- команда "открыть по выделению" открывает файл main.css? та же папка

**Comment by kvichans** [comment]
Поясните.
 - Подозреваю, что уже сейчас сработает "открыть", если выделен main.css. Это так?
 - Вы хотите, чтобы плаг-команда при отсутствии выделения, использовала тек-слово/выр-в-кавычках? Это можно. Только после реализации другой плаг-команды: расширяющееся выделение (как в Син). Это у меня в планах

**Comment by Alexey-T** [comment]
> при отсутствии выделения, использовала тек-слово

да. Вот это

**Comment by Alexey-T** [comment]
>сработает "открыть", если выделен main.css

конечно же. Что тут подозревать

**Comment by Alexey-T** [comment]
(up)

**Comment by Alexey-T** [comment]
Пач--сделано. надо взять мой word_proc.py
[cuda_ext-pch.zip](https://github.com/kvichans/cuda_ext/files/86329/cuda_ext-pch.zip)

**Comment by kvichans** [comment]
Я уже свой код из Син перетащил
Ваш посмотрю

**Comment by Alexey-T** [comment]
Посм. пач #6

**Comment by kvichans** [comment]
Почему такой (странный!) выбор *допустимых* символов для имени файла
`CHARS_FILENAME = string.ascii_letters + string.digits + '_/-=.,'`
?

**Comment by kvichans** [comment]
Доделал до определения либо слова, либо выражения в кавычках.

**Comment by Alexey-T** [comment]
Добавьте плис \ --а вот скобки не надо, потому что в css может быть так

`include(fname.css)`

не надо и <>*--этовещи их cmd.exe- ввод вывод и маска.

**Comment by kvichans** [comment]
Уже выложил. Скобки отсекаются при поиске слова до пробельного символа
