### ISSUE TITLE
New file, in folder of current file

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#33]
Wish
Cmd must see dir of current named tab. And make new empty file in this dir, after Save-as.

**Comment by kvichans** [comment]
Не понял.
Предлагаете создать и сохранить пустой файл?

**Comment by kvichans** [comment]
Создать пустой таб и вызывать диалог SaveAs с подходящим значением "папка для сохранения"?

**Comment by Alexey-T** [comment]
Последнее

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Пробуйте. Не все мелочи были очевидны

**Comment by Alexey-T** [comment]
Save as "n.php"- PHP lexer not setup

**Comment by kvichans** [comment]
Это вы про что? К ТЗ это какое отношение имеет?

**Comment by Alexey-T** [comment]
к ТЗ нет, но удобно если лекс поставить после save.
ошибка. "No seperator '{}' in selected lines"

**Comment by Alexey-T** [comment]
_('Warning: the command needs a named tab.')) лучше к констатнам

**Comment by kvichans** [comment]
>к ТЗ нет, но удобно если лекс поставить после save.

Почему Куд сам лекс не ставит при сохранении? Как плагин будет разбираться в дебрях связей между именами и лексерами?

>ошибка. "No seperator '{}' in selected lines"

Как повторить?

> лучше к константам

Это уже оформлено через `_()`, то есть готово к переводу.

**Comment by Alexey-T** [comment]
Куд должен ставить, верно
2) ошибка в слове  "No seperator

**Comment by kvichans** [comment]
2) fix (будет доступно при следующем крупном обновлении)

**Comment by Alexey-T** [comment]
3) где-то было "Command works only for named tab", лучше ее.

**Comment by kvichans** [comment]
3) "лучше ее" ? что ее?

**Comment by Alexey-T** [comment]
3) сделать константу вверху, юзать ее.

**Comment by kvichans** [comment]
3) Это лишнее. Константы в начале файла - рудимент, от которого нужно избавляться (только лень помешала это уже сделать). Технология `gettext` лучше: константы оборачиваются в `_()`, есть инструмент для извлечения их во внешний файл `messages.pot`, где их удобно рассматривать/править/переводить

**Comment by Alexey-T** [comment]
Решено
