### ISSUE TITLE
Comment-code 2

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#34]
Тут тоже - надо удалить код просто

**Comment by kvichans** [comment]
"тут" - это где?

**Comment by Alexey-T** [comment]
cuda_ext- код коментирования тоже остался как комент.

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Я, как автор плагина, могу позволить коду побыть под комментарием. Удалю позже.
Жизнь научила так себя вести с кодом. Ближе всего эта мудрость описывается армейской присказкой: "не торопись выполнять приказ, может быть его отменят".
