### ISSUE TITLE
(wish) MultiPaste dialog

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#35]
Вот такую фичу имеет новый Делфи, для пастинга выводов от DB, вот описание и скрин

http://docwiki.embarcadero.com/RADStudio/Berlin/en/MultiPaste

**Comment by kvichans** [comment]
А в Дельфи есть каретки? 
Диалог по ссылке дает сильно обрезанную функциональность кареток. Вот шаги для его замены
1. вставить строки из буфера
2. расставить каретки в начале строк
3. вставить начальный фрагмент
4. перевести все каретки в концы строк
5. вставить конечный фрагмент

Если последние три действия поместить в макрос, то можно даже многократно применять.
Итого - нет, wish не делать.

**Comment by Alexey-T** [comment]
я не знаю про новые Делфи (Берлин и тд), только это из вики.

**Comment by kvichans** [comment]
?

**Comment by Alexey-T** [comment]
Вы спросили- " в Дельфи есть каретки?"

**Comment by kvichans** [comment]
Это был риторический вопрос. Объяснял, почему не хочу делать это.
