### ISSUE TITLE
wish: Html commands: bold/italic

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#37]
на Ru-board просили такой код, который к выделениб делает html tags:

- bold, `<b>sel here</b>`
- italic
- underline

Можно сюда добавить?

**Comment by kvichans** [comment]
Я против "сюда". Запрос на специализированное применение, а плагин из общеполезных команд.

**Comment by Alexey-T** [comment]
выложу свой вариант.
