### ISSUE TITLE
Reformat comment

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#39]
Вот такой виш, это сложно сделать? https://www.reddit.com/r/SublimeText/comments/5ktek1/is_there_a_plugin_to_make_justified_alignment_for/

**Comment by kvichans** [comment]
Не понятно. Пример только намекает

**Comment by Alexey-T** [comment]
Команда re-wrap lines. Она должна спросить ширину, напр 60. Она удаляет в выделении символы коментов (line cmt). склеивает все в 1 строку. и разбивает строку на подстроки длины до 60.
Потом если она удалила символ комента, то полученные строки длины до 60, коментим обратно

**Comment by Alexey-T** [comment]
Лучше спросить символы комента- для просто текстов нет лекса, нет коментов, в примере это #.

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
я тогда запощу ссылку - на тот форум.

**Comment by kvichans** [comment]
Нужно выбрать название для метода
`ReWrap selected text by margin` подойдет?

**Comment by kvichans** [comment]
План:
1. Брать колонку отсечения из настроек Куд
`  //Fixed margin (vertical line) column.`
` "margin": 80,`
2. Брать символ(ы) комментариев из лексера. При лексер==None не убирать комментарии. 
3. Отказываться от изменений при нескольких каретках.
4. Брать полные строки, затронутые выделением.
5. Отказываться от изменений, если часть строк с комментарием, часть без.
6. Отказываться от изменений, если знаки комментарием расставлены не в одинаковой колонке

Нужно решить:
1. Нужно ли оставлять общие начальные пробелы?
Это позволит, например, преобразовать
```
···Lorem ipsum dolor sit amet, consectetur adipiscing
···elit. Sed malesuada arcu non urna finibus auctor. 
```
в
```
···Lorem ipsum dolor sit 
···consectetur adipiscing elit. 
···Sed malesuada arcu non urna 
···finibus auctor. 
```

**Comment by kvichans** [comment]
Символы `\t` внутри текста - это засада :)

**Comment by kvichans** [comment]
Требуется тестирование
Вот что я вижу:
1. Без лексера, то есть без комментариев
![rewrap-tab-int-bf](https://cloud.githubusercontent.com/assets/7419630/21568443/c0378a4c-cec5-11e6-88aa-bfd95b44d4dc.PNG)
превращается
![rewrap-tab-int-af](https://cloud.githubusercontent.com/assets/7419630/21568444/c0380558-cec5-11e6-929f-0f8302d489c5.PNG)

2. С лексером и комментариями
![rewrap-cmnt-tab-int-bf](https://cloud.githubusercontent.com/assets/7419630/21568445/c0389144-cec5-11e6-97d3-c01c7a97db9d.PNG)
превращается
![rewrap-cmnt-tab-int-af](https://cloud.githubusercontent.com/assets/7419630/21568442/c034b27c-cec5-11e6-824a-6680a6c4243f.PNG)

**Comment by Alexey-T** [comment]
План--
- все равно надо делать если кмт в разных колонках (пример - перепутал таб и пробелы)
- если лекса нет- и в начале строк стоят некие symbols - спросить- не символы коменты это?
пример - #, //

**Comment by Alexey-T** [comment]
- Что делать с индентом - часто нужно его убрать, тогда лучше дать checkbox в диалоге- сохранить ли индент. если индента нет, запретить check

**Comment by kvichans** [comment]
Сделал диалог.
Нужно продолжить тестирование

**Comment by Alexey-T** [comment]
fix: "save intend"-"Keep indents"

**Comment by Alexey-T** [comment]
dialog caption: "Re-wrap" pls

**Comment by kvichans** [comment]
Про титул диалога не понял. Сейчас `Re-wrap selected text`

**Comment by Alexey-T** [comment]
"intend"== собираться. indent.

**Comment by Alexey-T** [comment]
На Суб примере- работает

**Comment by kvichans** [comment]
fix стало `Keep indent`

**Comment by kvichans** [comment]
публикуем?

**Comment by Alexey-T** [comment]
Да

**Comment by kvichans** [comment]
опубликовал

**Comment by Alexey-T** [comment]
титул пуст. Может ОС не вывело. Надо короткий "Re-wrap"

**Comment by kvichans** [comment]
Может комаду лучше назвать "Re-wrap lines"? И титул будет такой же

**Comment by Alexey-T** [comment]
Да, норм.
