### ISSUE TITLE
Wish: Join lines/ Split lines

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#42]
Виш, на 2 команды

- join lines- сцеплять выд-е в 1 строку (через пробел, не делать 2+ пробела на сцепке)
- split lines- разбить строки в выделении на строки до длины Н (Н запросить. msg_box.)

пример вывода, н=15
````
ddd ddd ddddddd
ddddd ddddd dd
dddd dddddd ddd
ddd ddddd ddd
```

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
"split lines" уже сделана - см команду `Re-wrap lines by margin`

**Comment by Alexey-T** [comment]
Ok,
если можно, дайте ей еще имя "Re-wrap lines by margin/ split lines".

**Comment by kvichans** [comment]
Может лучше 
  "Re-wrap lines by margin (split lines)"
?

**Comment by Alexey-T** [comment]
да, можно так, надо чтобы было "split".

**Comment by kvichans** [comment]
ok

**Comment by Alexey-T** [comment]
А команду join не делали?

**Comment by kvichans** [comment]
Да, давно уже работает
  plugin: CudaExt: Join selected lines

**Comment by Alexey-T** [comment]
Спасибо..
