### ISSUE TITLE
Cmd ReIndent

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#43]
Добавить команду для подмены начальных сдвигов у выделенных строк

**Comment by kvichans** [comment]
Рабочий вариант:
![reindent](https://cloud.githubusercontent.com/assets/7419630/23201413/89fec798-f8ea-11e6-92e6-1eb15b738c08.png)

**Comment by Alexey-T** [comment]
Done

**Comment by kvichans** [comment]
Да, уже давно
