### ISSUE TITLE
Wish: rename also item in project

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#45]
http://synwrite.sourceforge.net/forums/viewtopic.php?f=19&t=1786

**Comment by kvichans** [comment]
Какое API нужно вызывать, чтобы в проекте изменилось отображаемое имя?

**Comment by Alexey-T** [comment]
В плагине cuda_project_man вызвать метод action_refresh
через Апи Куды (app_proc)

**Comment by kvichans** [comment]
Поясните подробнее
1. Могу в cuda_ext выполнить import cuda_project_man. А как узнать, что сейчас открыт проект?
2. Какой вызов обновит дерево Проекта?

**Comment by Alexey-T** [comment]
Сложно- потом посм.

**Comment by Alexey-T** [comment]
cuda_project_man- не дает метода "переименую это в это". Там есть rename -не то. надо как-то делать метод. и пускать его http://wiki.freepascal.org/CudaText_API#Plugin_calls

**Comment by kvichans** [comment]
Вы открыли - вам и решать
