### ISSUE TITLE
To open all files in dir and all subdirs

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#47]
From [Cud](https://github.com/Alexey-T/CudaText/issues/882#issuecomment-302997293)

**Comment by kvichans** [comment]
Нужно открыть "все файлы" без маски на имя?

Можно показать dlg_input, чтобы задать маску. Это совсем просто реализовать.
Тогда открыть действительно все - это задать маску "*".

**Comment by kvichans** [comment]
Дал маску. Годится?

**Comment by Alexey-T** [comment]
chr(13)+'   '+(chr(13)+'   ').

Правильно исп-ть "\n", т.е chr(10)

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Спасибо за команду. В Атом ее просили, увидел.

**Comment by kvichans** [comment]
Опубликовал
