### ISSUE TITLE
Commd "Wrap selection in HTML tag"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#48]
Плс, посм. как работает хоткей Alt+Shfift+W в Субл.
Он берет выделение, кладет его в тег p

`<p>selected</p>`

и ставит 2 керетки на начало и конец тега
Говорят что это удобно!

**Comment by kvichans** [comment]
Это слишком маленький пример.
Как это обобщить?

**Comment by Alexey-T** [comment]
он обобщается на все HTML tags.

**Comment by kvichans** [comment]
Как?

**Comment by Alexey-T** [comment]
2 каретки. печатаю и меняется р на например frame.

**Comment by Alexey-T** [comment]
Каретки уже с выделенным "p"

**Comment by kvichans** [comment]
Тогда это не обобщение, а "бонус" от описанного использования.

**Comment by Alexey-T** [comment]
не понял... почему хоткей не хорош?

**Comment by kvichans** [comment]
Итого: нужна команда 
- окружающая выделение отк/закр тегом
- по умолч. это тег <p>....</p>
- после вставки тегов нужно выделить имя тега в двух местах

Так?

**Comment by Alexey-T** [comment]
Он еще работает если нет выделения. тогда делается новый таг p с 2 каретками также

**Comment by Alexey-T** [comment]
Да, так. Плюс см. выше когда нет выделения

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
Когда нет выд-я

- он делает тег `<p></p>`
- два выделения
- и два маркера как в снипетах--- чтобы ТАБ прыгнул внутрь тега. второй ТАБ прыгнут за теги

**Comment by kvichans** [comment]
Тогда - может это такой снип?

**Comment by Alexey-T** [comment]
Это работает как снип

**Comment by kvichans** [comment]
в чем отличие?

**Comment by Alexey-T** [comment]
Юзер не должен делать снип и вызывать снип

**Comment by kvichans** [comment]
Верно ли, что разница только в том, что на снип СЕЙЧАС нельзя назначить хоткей?

**Comment by Alexey-T** [comment]
еще разница- снип надо печатать и жать Таб.

**Comment by Alexey-T** [comment]
Может это надо в плаг HTML Ops?

**Comment by Alexey-T** [comment]
Пока начал делать- в плагин HTML Ops.
так что не надо

**Comment by Alexey-T** [comment]
Сделал- вот код
https://github.com/CudaText-addons/cuda_html_ops/blob/master/__init__.py
