### ISSUE TITLE
3 checks for API ver

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#49]
FROM_API_VERSION    = '1.0.119'
 MIN_API_VER_4_REPL  = '1.0.169'
+FROM_API_VERSION    = '1.0.182'     # PROC_SPLITTER_GET/SET, LOG_CONSOLE_GET_MEMO_LINES
 
Зачем то 3 проверки

**Comment by kvichans** [comment]
Где три проверки? Несколько объявлений одной переменной вижу.
Мне это нужно, чтобы знать какие фичи АПИ добавлялись

**Comment by Alexey-T** [comment]
Т.е. 2 проверки на 2 версии
Можно сделать на одну

**Comment by kvichans** [comment]
Не нужно ничего менять

**Comment by kvichans** [comment]
Точнее: MIN_API_VER_4_REPL отомрет, когда я переделаю код на ed.replace_lines
А два объявления FROM_API_VERSION останутся
