### ISSUE TITLE
Align by separator: support mul-selections like Atom

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#50]
Атом умеет так
```
dde=dd
dddee=dd
eeeeeeааа=ee
d=ed
ee=eeddd
```
тут 2 выделения. строка 1-2 и второе строка 4-5.
команда выровнит два выделения, и не тронет строку 3.
```
dde   = dd
dddee = dd
eeeeeeааа=ee
d     = ed
ee    = eeddd
```

**Comment by kvichans** [comment]
Диклог в каманде "выр по разделителю" уже запоминает ширину. Проще его несколько раз вызвать, чем составлять сложное выделение.
Итого - нет, не стоит усилий
