### ISSUE TITLE
Need 4 new commands: Go to next modified line

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#51]
- Go to next modified line
- ,.. previous ..
- Go to next modified/saved line
- ... previous ..

Это делается через ed.get_prop(PROP_LINE_STATE)
В Сине есть эти кмд.

**Comment by kvichans** [comment]
Хорошие команды
ToDo

**Comment by Alexey-T** [comment]
Наверное да

**Comment by kvichans** [comment]
Хочу добавить команды для перехода к любым строкам бывшим в работе: измененные, сохраненные, добавленные.
Нужно выбрать имя команды.
`Jump to next worked lines` - понятно? корректно?

**Comment by kvichans** [comment]
Тестируем новые команды
CudaExt: Jump to next changed lines
CudaExt: Jump to previous changed lines
CudaExt: Jump to next saved lines
CudaExt: Jump to previous saved lines
CudaExt: Jump to next worked lines
CudaExt: Jump to previous worked lines

**Comment by kvichans** [comment]
Повесил `next/prev worked` на `Shift+Ctrl+Alt+dn/up`
Классно!!

**Comment by Alexey-T** [comment]
'worked' не видел слово, это "работал". рабочие это 'working'/ 'work'

**Comment by kvichans** [comment]
Ок

**Comment by Alexey-T** [comment]
Можно обновить версию.

**Comment by Alexey-T** [comment]
Плс, пишите в history подробнее, а то непонятно даже мне если я не просил это
пример - "добавилась команда ".......", она делает ......"

**Comment by kvichans** [comment]
Во жизнь пошла веселая: вы просите меня писать подробнее, а не я вас :)

**Comment by Alexey-T** [comment]
1.2.6 (2016-12-30)
added: rewrap by margin

Непонятно что это- тк команды `rewrap` нет
Added cmd "Re-wrap/split by margin"

1.2.5 (2016-09-13)
removed: edit_strcomment_chars is moved to plugin cuda_comments

Тут неопнятно, что за штука и куда уехала
Commands "Edito comment chars" removed to plugin "Comments"

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Можете просто отредактировать сами
