### ISSUE TITLE
Cmd need "Fold selected block"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#53]
Расписано здесь
https://github.com/Alexey-T/CudaText/issues/939

АПИ вот тут
http://wiki.freepascal.org/CudaText_API#folding

не хочется добавлять в ядро. Трудный момент -
при правке, ядро очищает список fold ranges, ваш фолд пропадет

**Comment by kvichans** [comment]
ТЗ непонятное. Давайте прояснять
Допустим появится команда для скрытия произвольного набора строк. 
1. Что будет с этим фолд-диапазоном дальше - какой у него срок жизни?
2. Что будет происходить с ним при добавлении/удалении строк?

**Comment by Alexey-T** [comment]
Про срок написал-
Life time of this range is until lexer analisys runs (it clears ranges and adds ranges from lexer).

**Comment by Alexey-T** [comment]
2- Он удалится
3- Плагин просто поправить
4- будут работать ОК

апи1- item_x это символ в стр где начался range
апи2- не влияет вроде бы.

**Comment by Alexey-T** [comment]
Пример
>>> ed.folding(FOLDING_ADD, item_x=0, item_y=4,item_y2=6, item_hint='hhhhhhhhhhhhhh')

**Comment by kvichans** [comment]
Пока не понял сути ТЗ. 
Чем КРОМЕ вызова `ed.folding(FOLDING_ADD...)` может помочь плагин?

**Comment by Alexey-T** [comment]
Еще надобы запомнить range и делать его при каждой правке в on_change (надо может еще паузу в н мсек)

**Comment by kvichans** [comment]
я такой ерундой заниматься не хочу

**Comment by Alexey-T** [comment]
Может тогда надо допилить Апи

**Comment by Alexey-T** [comment]
Начал делать сам https://github.com/CudaText-addons/cuda_fold_sel
