### ISSUE TITLE
Wish:  4 paragraph commands for simple text

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#54]
a. Go to Beginning of Paragraph
b. Go to End of Paragraph
c. Go to Previous Paragraph
d. Go to Next Paragraph.

На форуме просят эти команды
Параграфы отделяются пустыми строками (1 иои больше).

**Comment by kvichans** [comment]
Чуть дополнил: 
- если каретка **уже в начале** параграфа, то перед командой `Go to Beginning` отрабатывает `Go to Prev`
- если каретка **уже в конце** параграфа, то перед командой `Go to End` отрабатывает как `Go to Next`

Классная штука. Буду постоянно пользоваться.
Выложу вместе с align-командами.

**Comment by Alexey-T** [comment]
Может не надо  "дополнил", т е опцию ввести?

**Comment by kvichans** [comment]
Нужно не нам решать. Может это "логичное поведение" есть у тех прог, на которые ссылается qwerky.

**Comment by kvichans** [comment]
Тестируем

**Comment by Alexey-T** [comment]
Работает, спасибо.
