### ISSUE TITLE
Wish: 4 align commands for 4 paragraph types

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#55]
http://synwrite.sourceforge.net/forums/viewtopic.php?p=10816#p10816
Описано что такое 4 типа параграфа для писателей

Просят 4 команды для всех типов параграфов

Justification would include:
a. Left justified (smooth left edge, ragged right edge)
b. Right justified (ragged left edge, smooth right edge)
c. Center justified (ragged left/right edge)
d. Fully justified (smooth left/right edge)

smooth- выровненый край
ragged- грубый край
fully- значит раздвигать пробелами

удобно сделать 4 кмд для  4 типов через 1 диалог с radiogroups

**Comment by kvichans** [comment]
ToDo
ТЗ:
Для текущего параграфа (от начала или пустой строки до конца или пустой строки) 
- удалить все лишние пробелы
- найти строку максимальной длины 
- и в остальных строках добавить пробелов (в начале и/или в конце, между словами). 

Только не понял зачем нужен диалог? Все команды добавляют или убавляют пробелы в строках текущего параграфа. Не вижу, что еще тут можно уточнять.

**Comment by Alexey-T** [comment]
Не совсем-- просят делать align по right margin, строку искать не надо,надо склеить все строки

**Comment by Alexey-T** [comment]
- В длг можно выбрать "тип параграфа", если юзер хочет поменять все параграфы (select all)

**Comment by Alexey-T** [comment]
Назвать кмд можно так

- Align paragraph(s): Left justify
- Align paragraph(s): Right justify
- Align paragraph(s): Center justify
- Align paragraph(s): Fully justify

**Comment by kvichans** [comment]
Разве `right margin` не задано глобально? 
Если "да", то остальное можно без диалога: применять команды ко всем выделенным параграфам. 
Если "нет", то нужно спросить только одно число - это через `dlg_input` можно сделать.

**Comment by Alexey-T** [comment]
- да, задан
- но надо спросить 2 выбора - тип параграфа (переделать текст в этот тип) + тип align

**Comment by kvichans** [comment]
>тип align

понимаю

----
>тип параграфа

не понимаю. Что это?

**Comment by Alexey-T** [comment]
http://synwrite.sourceforge.net/forums/viewtopic.php?p=10816#p10816
Описано что такое 4 типа параграфа

indented
```
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Etiam ultricies sagittis
orci, nec consequat dolor consequat ac.  Nulla eleifend rutrum semper.  Sed fringilla,
ligula eu gravida tempor, quam magna blandit dolor, quis imperdiet sapien erat eu nibh.
Nunc rutrum pulvinar nulla in facilisis.  Quisque feugiat purus in leo condimentum non
congue eros consectetur.  Praesent dictum consequat nulla, bibendum rhoncus enim
adipiscing et.  Pellentesque mi tellus, ornare id mattis ac, sollicitudin a erat.  Maecenas
sit amet vehicula odio.
```

outdented
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Etiam ultricies sagittis orci,
          nec consequat dolor consequat ac.  Nulla eleifend rutrum semper.  Sed fringilla,
          ligula eu gravida tempor, quam magna blandit dolor, quis imperdiet sapien erat eu
          nibh.  Nunc rutrum pulvinar nulla in facilisis.  Quisque feugiat purus in leo
          condimentum non congue eros consectetur.  Praesent dictum consequat nulla,
          bibendum rhoncus enim adipiscing et.  Pellentesque mi tellus, ornare id mattis ac,
          sollicitudin a erat.  Maecenas sit amet vehicula odio.```

non-indented
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Etiam ultricies sagittis orci,
nec consequat dolor consequat ac.  Nulla eleifend rutrum semper.  Sed fringilla, ligula
eu gravida tempor, quam magna blandit dolor, quis imperdiet sapien erat eu nibh.  Nunc
rutrum pulvinar nulla in facilisis.  Quisque feugiat purus in leo condimentum non congue
eros consectetur.  Praesent dictum consequat nulla, bibendum rhoncus enim adipiscing
et.  Pellentesque mi tellus, ornare id mattis ac, sollicitudin a erat.  Maecenas sit amet
vehicula odio.
```
block-indented
```
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Etiam ultricies sagittis
          orci, nec consequat dolor consequat ac.  Nulla eleifend rutrum semper.  Sed
          fringilla, ligula eu gravida tempor, quam magna blandit dolor, quis imperdiet sapien
          erat eu nibh.  Nunc rutrum pulvinar nulla in facilisis.  Quisque feugiat purus in leo
          condimentum non congue eros consectetur.  Praesent dictum consequat nulla,
          bibendum rhoncus enim adipiscing et.  Pellentesque mi tellus, ornare id mattis ac,
          sollicitudin a erat.  Maecenas sit amet vehicula odio.
```

**Comment by Alexey-T** [comment]
К всем 4 типам можно применить все 4 align

**Comment by kvichans** [comment]
Понял.
Нужен еще один глобальный параметр: `left margin`.
При его значении 0 все типы параграфов сливаются.

**Comment by kvichans** [comment]
Нет. Не все понял :)
Для `Full justify` вы дали примеры.
Для `Left justify` сам понимаю.

Как сочетаются `indented/outdented` типы с `Right/Center justify`?

**Comment by Alexey-T** [comment]
Спросил в форуме

**Comment by Alexey-T** [comment]
Ответили http://synwrite.sourceforge.net/forums/viewtopic.php?p=10824#p10824
сказали что есть кривые варианты (r-align, center-align + некоторые типа параг.)
- их или можно сделать как удобно или задисеблить

**Comment by Alexey-T** [comment]
Просит учесть 3 типа разделения параграфов. софт должен уметь читать+писать все типы когда пишется много

1. Beginning a paragraph with a first-line indentation,
2. Separating one paragraph from another with a blank line, and
3. Ending a paragraph with a <return> (line-end), making the entire paragraph a single line, and relying upon the software to format the display of the paragraph.

Each method ..should be handled by a complete software solution.

**Comment by kvichans** [comment]
Не понял про что это

**Comment by Alexey-T** [comment]
вы читаете параграфы - разделение по blank line.
Он предлагает 3 типа разделения. blank line, EOL, indent. все используются писателями.

**Comment by kvichans** [comment]
EOL то здесь причем? Если параграф уже состоит из одной строки, то что с ним можно сделать?

Про indent не понял.

Скоро закончу с выравниванием параграфов, разделенных пустыми строками.
Полагаю, что остальные разделители - отказать.

**Comment by Alexey-T** [comment]
За left margin можно взять опц indent_size (если >0)?

**Comment by kvichans** [comment]
Ага! Особенно удобно, если значение отрицательное :)
Нет. Будет три новых ключа для user.json
`right_margin`
`left_margin`
`left_margin_1st`

**Comment by kvichans** [comment]
Имена ключей не окончательные. Есть варианты?

**Comment by Alexey-T** [comment]
Один префикс-
margin_right (по дефолту брать из margin)
margin_left (один для всех типов блоков)
зачем _1st?

**Comment by kvichans** [comment]
Для первой строки параграфа

**Comment by kvichans** [comment]
Хорошо бы margin в ключах заменить на что-то другое - более напоминающее, что это будет применяться для параграфов

**Comment by kvichans** [comment]
Вот так
```json
    "margin_right": 13,
    "margin_left": 4,
    "margin_left_1": 2,
```
нормально?

**Comment by kvichans** [comment]
Вот так их можно будет менять:
![options to align paragraphs key in user json](https://user-images.githubusercontent.com/7419630/28315434-19131b06-6bc7-11e7-8d99-99b5ad905ae9.png)

**Comment by kvichans** [comment]
Тестируем

**Comment by Alexey-T** [comment]
А что покажет диалог "Align paragraph"?
если можно выбрать тип параграфа то можно просто 2 опции

**Comment by kvichans** [comment]
Тип параграфа выбрать нельзя - это лишнее.
Задается смещение первой и остальных строк - этого достаточно

**Comment by Alexey-T** [comment]
Вы сделали обще

можно назвать лабелы так-

- Paragraph right margin
- Indent of first paragraph line
- Indent of other paragraph lines

места не жалко

**Comment by Alexey-T** [comment]
qwerky дал такое предл. -
при full justify вы все пробелы распределяете слева и слева их больше.
Он просит-

- для первой строки параграфа распределять справа
- для 2й слева
- для 3й справа
- и тд

**Comment by kvichans** [comment]
Да, проблему понимаю. Она глубже, чем ее видит qwerky.
Буду думать

**Comment by Alexey-T** [comment]
записал в новый issue.
