### ISSUE TITLE
"Set nearest Tree node"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#57]
Что она делает? по названию непонятно.

**Comment by kvichans** [comment]
Делает текущим тот узел в Дереве, диапазон которого ближе всего расположен к каретке.
(Создавалось как вспомогательный вызов для навигации по тексту без  отображения Дерева)

**Comment by Alexey-T** [comment]
Rename?
"Set active node of Code Tree, nearest to caret"

**Comment by kvichans** [comment]
ок
