### ISSUE TITLE
Trouble on open file

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#62]
Самое раздражающие поведение Куд сейчас такое
- Открываю большой файл с кодом (например, из Фиф)
- Начинаю что-то в файле делать (обычно это перемещения каретки или скролы)
- Куд параллельно делает что-то свое (похоже строит дерево)
- И примерно через 1-2 сек - бац: Куд перемещает скрол и может быть что-то еще делает (похоже он только к этому моменту понял как показать файл после открытия: какой нужен скрол и куда поставить каретку)

**Comment by Alexey-T** [comment]
не в том репо?

**Comment by kvichans** [comment]
Ну да
