### ISSUE TITLE
Global bookmarks

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#64]
Некоторые едиторы имеют такие букмарки (1..9)

- ставим в любом табе букмарк n
- из любого таба и группы "goto bkmk n" прыгает в старый таб и старое место
(открывает старый таб если закрыт)

**Comment by kvichans** [comment]
Какую можете предложить идею реализации?

Я пока могу только предложить показ всех intext-bookmarks

**Comment by Alexey-T** [comment]
Сохранять эти букмарки в global_bookmarks.json,
при открытии файла ставить их

**Comment by kvichans** [comment]
"Ставить"? Какое АПИ?

**Comment by Alexey-T** [comment]
Ставить- http://wiki.freepascal.org/CudaText_API#bookmark

**Comment by kvichans** [comment]
Попробую

**Comment by kvichans** [comment]
Хороший виш. Пока не понял, как из плагина перейти на какой-нибудь из букмарков. Подскажите

**Comment by Alexey-T** [comment]
.json хранит 

- номер
- имя файла
- н строки

при переходе на букмарк

- делаем file_open(fname)
- переходим на н строки

**Comment by kvichans** [comment]
1. Это обычные bookmark? Если да, то как плагин узнает, что пользователь поставил новый такой?
2. Сейчас уже есть сохранение обычных bookmark в сессии?
3. В АПИ уже есть все для сбора информации о текущих расставленных букмарках в каждом из открытых файлов. Плагин может их все показать пользователю и пользователь выберет на какой перейти. Достаточно дать АПИ для выполнения перехода. Так?

**Comment by Alexey-T** [comment]
2. Есть
1. Плаг даст команды « поставить глоб букмарк н».
Ещё хорошо бы плаг дал этим букмаркам свои иконки ( можно н штук для номеров 1.. н).

**Comment by kvichans** [comment]
3. Какое отношение "команды « поставить глоб букмарк н»" имеют к вопросу "как переместить каретку на один из букмарков"?

Давайте рассмотрим переформулировку ТЗ. Можно делать не "глоб букмарк", за которые отвечает плагин, а рассматривать уже установленные букмарки, через новый плаг как глобальные. Если восстановление через сессию уже работает, то в АПИ не хватает только команды "перейти"

**Comment by Alexey-T** [comment]
3. Никакого, я ставил номер один а не 3

**Comment by Alexey-T** [comment]
Думал мы хотим ставить спец глобальные букмарки.

**Comment by kvichans** [comment]
"Мы хотим" разного. Я очень не люблю _расщепление_ = близкие функциональности, которые легко перемешиваются. Если делать новые букмарки, то будет как раз это - они будут путаться с обычными. А вот дорастить обычные до глобальных - это ИМХО замечательно.
Со стороны Куд все уже есть, кроме "перейти".
Со стороны плага можно фантазировать про
- Показать дерево букмарков - по-файлово
- Показать букмарки, сортированные по их использванию (от АПИ нужно событие "выполнен переход")
- Команда "Вернуться на [пред-[пред-]]последний использованный букмарк"
- и т.п.

**Comment by Alexey-T** [comment]
Хорошо, а что тогда надо от меня в этом тз?

**Comment by kvichans** [comment]
Дополнить АПИ
- Команда для перехода на существующий букмарк в конкр.файле
- (может быть) Событие "Был переход на такой-то букмарк в  таком-то файле

**Comment by Alexey-T** [comment]
1- это же просто прыг на номер строки ed.set_caret
2-  евент сработает не всегда. Например вы прыгнете- то нет

**Comment by Alexey-T** [comment]
1- и ещё set_prop(prop_line_top, z)

**Comment by kvichans** [comment]
1. Да, разобрался. Могу сам сделать переход. 
2. Без события не получится сделать сортировку "по последним вызовам", учитывающую переходы "без плага". Но еще остается возможность помнить переходы "с помощью плага" - уже что-то

**Comment by Alexey-T** [comment]
2- Вы же можете  ловить on-caret и видеть что юзер встал на строку н

**Comment by kvichans** [comment]
Как я смогу отличить простой клик от перехода на б.марк ?

**Comment by Alexey-T** [comment]
Никак, подумаю про евент

**Comment by kvichans** [comment]
Давайте дожмем.
Отображение уже есть #87 Можно доделать до показа только нумерованных марок.
Нужно сделать сохранение+восстановление.
Я до сих пор думаю, что хранение в сессии - это лучший вариант.

**Comment by Alexey-T** [comment]
Можно доделать хранение только марок плагина numbered bookmarks? А не всех. Напр не надо для cudalint.

**Comment by kvichans** [comment]
Расскажите, что за марки ставит cudalint и почему их не нужно хранить?

**Comment by Alexey-T** [comment]
Желтые марки на ошибках в файле. не нужно потому что линтинг надо пускать руками.

**Comment by kvichans** [comment]
Я не пользуюсь cudalint 
Есть ли различие у марок от cudalint и нумерованных от cuda_num_bookmarks?

**Comment by Alexey-T** [comment]
Cudalint marks требую настройки при старте плагина. num bookmarks - вроде нет.

**Comment by kvichans** [comment]
Допустим я буду делать сохранение num bm. Как их отличить от Cudalint marks?

**Comment by Alexey-T** [comment]
Марки cudalint имеют kind 20...22.

**Comment by kvichans** [comment]
Почему бы не сохранять в сессии все марки с 0<=kind<=max_kind, а max_kind сделать 10?

**Comment by Alexey-T** [comment]
Согласен, наверно сделаю.

**Comment by kvichans** [comment]
Тогда я еще добавлю в cuda_ext команды просмотра/перехода для нуменованных (1..9) марков

**Comment by kvichans** [comment]
Сори. Я только сейчас понял, что исходное ТЗ включало "открыть файл с маркой". 
ИМХО это лишнее, так как
- для этого нужно заводить хранение (это само по себе не трудно), 
- которое не привязано ни к сессии, ни к проекту (это уже плохо)
- удалить такую марку можно будет только открыв файл
- значит будет идти замусоривание (поставили марку, файл закрыли, загр. др.сессию)

Для открытия файлов на нужно месте, можно доработать плагин Фавориты

**Comment by Alexey-T** [comment]
OK, упростите ТЗ

**Comment by kvichans** [comment]
Если из ТЗ убрать "открыть файл с маркой", то осталось только сохранение/восстановление - диалог для показа и перехода уже есть.

Вы сделаете хранение 1<nkind<10 в сессии и `history files.json`?

**Comment by Alexey-T** [comment]
Как раз сделал.

**Comment by kvichans** [comment]
Проверяю на 1.43.1.0
- Открыл файл
- Поставил [1]-марку
- Закрыл файл
- Открыл его же 
- Нет марки

Если то же самое сделать с обычной маркой, то она сохраняется (видна в `history files.json`)

**Comment by Alexey-T** [comment]
Куд должен писать в сессию ключ bm_kind, он есть ? Если нет то сборка плохая

**Comment by kvichans** [comment]
Почему только в сессию?
До этого марки писались **и** в сессию, **и** в history files.json

**Comment by Alexey-T** [comment]
Да конечно, пишется и туда и туда

**Comment by kvichans** [comment]
Описал выше шаги: в history files.json не пишется

**Comment by Alexey-T** [comment]
Бета новая

**Comment by kvichans** [comment]
Теперь все работает нормально

**Comment by kvichans** [comment]
Ой!
Я только что увидел, что в одном файле можете быть только одна [2]-марка.
1. Это зачем так? 
2. На каком уровне это реализовано?
3. Можно ли ослабить это, чтобы расставлять столько одинаковых нум-марок, сколько захочется?

**Comment by Alexey-T** [comment]
1- также как Делфи ide
2- на уровне плагина num marks
3- да сделать плагин

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Плагин оч маленький

**Comment by kvichans** [comment]
уже разобрался
