### ISSUE TITLE
Paragraph fully justify - spaces

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#65]
при full justify вы все пробелы распределяете слева и слева их больше.
qwerky просит-

-    для первой строки параграфа распределять справа
-    для 2й слева
-    для 3й справа
-    и тд

**Comment by kvichans** [comment]
Думаю..

**Comment by Alexey-T** [comment]
не решено

**Comment by kvichans** [comment]
Похоже единственного пользователя команд "выравнивание слов в параграфах" не удержали - наколеночные решения не могут состязаться с промышленными.
Не беда - остались общеполезные команды переходов на начало/конец параграфа.

Предлагаю закрыть

**Comment by Alexey-T** [comment]
закроем.
