### ISSUE TITLE
Wish: Align current line by margin

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#66]
>SynWrite also had a "Center Line" command, which would center the current line based on right margin. This can now be done using the new paragraph commands, but requires modifying the paragraph settings... need new command.

from forum.

**Comment by kvichans** [comment]
Ок. Позже

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Поскольку речь об отдельных строках (а для целых параграфов уже есть команды), видимо нужны две команды:
Все строки, задетые текущим, единственным выделением, 
- центрировать по ширине margin
- прижать вправо к margin

Так?

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Требуется уточнение ТЗ
Какими символами сдвигать содержимое строки?
Единственный случай, когда понятно _чем_, это 
- в начале/конце строки нет chr(9)
- и `"tab_spaces": true`, то есть **нужно** использовать пробелы.

А в остальных случаях как? Отказываться от внесения изменений?

**Comment by Alexey-T** [comment]
Если в начале или середине таб, то можно при пуске сказать- Some lines contain tab-chars. Do you want to replace tabs to spaces and continue? Ok cancel

**Comment by kvichans** [comment]
"Можно"?  Вроде исходным был код Син. Там это как было?

**Comment by kvichans** [comment]
Выложил в ГХ
Сделал так
- Если Таб не пробельный, то _отказ_ со словами `Fail to use Tab to align`.
- Все строки затронутые выделением (мб не одним) очищаются от **концевых** пробелов и табов,
- Потом дополняются пробелами для выравнивания, если они короткие,
- Либо остаются очищенными, если длиннее `margin`

**Comment by Alexey-T** [comment]
Работает нормально. спасибо.

**Comment by Alexey-T** [comment]
можно строку так - "Cannot align lines indented by tab-chars"

**Comment by kvichans** [comment]
Уже опубликовал. Новая строка будет при след. релизе

**Comment by kvichans** [comment]
В вашем варианте: `Cannot align lines indented by tab-chars` - причина в самих строках. А я отказываюсь при опции `"tab_spaces":false`, до **до** анализа строк
