### ISSUE TITLE
Wish: command "Fill block by string"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#69]
forum:
>SynWrite function (plugin?) not in CudaText: Fill Block -- allow to fill entire selection with either single character or string of text.

**Comment by kvichans** [comment]
Спросить строку и заполнять ее копиями?

Делать для всех типов выделений?

**Comment by Alexey-T** [comment]
Посм.позже, в син команда уже не работает

**Comment by kvichans** [comment]
Еще актуально?

**Comment by Alexey-T** [comment]
Спросил qwerky.

**Comment by kvichans** [comment]
Первый вариант готов.
В этом варианте плагин проходит по всех непустым выделениям без EOL-ов внутри и делает замену выделенной части на размноженную строку от пользователя.

**Comment by Alexey-T** [comment]
Надо сказать qwerky.

**Comment by kvichans** [comment]
Уже :)

**Comment by Alexey-T** [comment]
Можно релизнуть плаг

**Comment by kvichans** [comment]
Совсем не очевидно, что пропускать выделения с EOL-ами это правильно

**Comment by kvichans** [comment]
Подождем реакции qwerky
