### ISSUE TITLE
Users cannot install my plugins

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#72]
Все мои плагины не отображаются в диалоге `Install`, хотя в `Update plugins` они есть.

**Comment by Alexey-T** [comment]
История 1.15- все пункты теперь в 2 списках -install, reinstall

**Comment by kvichans** [comment]
Есть в моей сборке 1.15.0 баг? 
В следующей сборке будет нормально?

**Comment by kvichans** [comment]
А-а-а
Уже установленные пропускаются. :)
