### ISSUE TITLE
"open all files in dir and subdirs" long message

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#79]
Too big window
![dlg](https://user-images.githubusercontent.com/4154978/30818902-95996ed4-a225-11e7-9b18-33a4fb16af79.png)

**Comment by kvichans** [comment]
Можно показать так:
Файл1
Файл2
....
ФайлN-1
ФайлN

Ок?

**Comment by Alexey-T** [comment]
OK

**Comment by kvichans** [comment]
![default](https://user-images.githubusercontent.com/7419630/30849461-16e11ebc-a2ab-11e7-9b3d-929b351fe5a8.png)

Нормально?

**Comment by Alexey-T** [comment]
Для нетбука с малым экраном не очень

**Comment by Alexey-T** [comment]
после "..." можно ничего не писать.

**Comment by kvichans** [comment]
Сколько оставить позиций?

**Comment by Alexey-T** [comment]
10 строк.

**Comment by kvichans** [comment]
ок
и публикую
