### ISSUE TITLE
Bad help for Reindent

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#80]
первый раз заюзал (после тестов). Что это значит- все эти 2б, две точки. ничего не понял честно. ввел просто 4 в поле-1, и получил креш.

поясните текст. "enter '2b' or '..', 't' for TAB".

**Comment by Alexey-T** [comment]
наверное надо ввести число + "б" для пробелов или "т" для таба. тогда надо так-
"For 2 spaces, enter '2b'. For tab-char, enter 't'".

**Comment by kvichans** [comment]
Переделал.
Теперь можно для пробелов использовать
- сами пробелы (не видно, но просто)
- точки
- <число>b
Подсказка перенесена в тултип
![default](https://user-images.githubusercontent.com/7419630/35793812-4157b068-0a64-11e8-9e76-96daee0cb884.png)

Можно закрыть?

**Comment by Alexey-T** [comment]
"to point" не говорят.  "to specify", "to enter".

**Comment by kvichans** [comment]
Заменю на "to specify"

**Comment by Alexey-T** [comment]
Можно закрыть
