### ISSUE TITLE
Readme txt file not packed into zip

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#82]
text about tab-switcher, deleted in zip distro

**Comment by kvichans** [comment]
Не понял
Удалить целый файл? какое у него имя?
Удалить фрагмент из readme?

**Comment by Alexey-T** [comment]
Вы удалили из дистро третий текст файл readme

**Comment by kvichans** [comment]
Добавил
plugin.CudaExt.zip выложил на СФ
