### ISSUE TITLE
Wish: command "Expand selection to word"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#83]
@kvichans 
We need command in CudaExt:
text has N ocurences of a word. Caret is on e.g. 2nd occurence. 

- Ctrl+D - 2nd occurence selected (under caret), 
- Ctrl+D - 3rd occurence selected [2 carets], 
- Ctrl+D - 4th occurence selected [3 carets]...

Many apps have it: Sublime, Atom, VSCode...

**Comment by kvichans** [comment]
А что должно происходить по этой команде, если предыдущее вы

**Comment by kvichans** [comment]
Может поменять ТЗ?:
- Если нет выделения, то выделить слово
- Если есть выделение, то найти следующий **такой же** фрагмент и тоже выделить его
- Если есть несколько выделений и все они содержат одинаковые фрагменты, то найти и выделить еще один такой же
- Иначе ничего не делать

**Comment by Alexey-T** [comment]
Сделать так же как сделано в Субл

- если не слово- искать такой же блок, выделять его
- если разные выделения- множить последнее

**Comment by Alexey-T** [comment]
(не проверять что одинаковые выделения. просто множить последнее)

**Comment by kvichans** [comment]
ТЗ:
- Если нет выделения, то выделить слово
- Если выделен фрагмент[ы], то найти следующий такой же [как последний] и его выделить 

Годится?

**Comment by Alexey-T** [comment]
годится.

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
следущий- искать от позиции посл. выделения.

**Comment by Alexey-T** [comment]
В конце делать скролл к новой каретке (если делали новую)

**Comment by kvichans** [comment]
ok

**Comment by Alexey-T** [comment]
когда хотите сделать?

**Comment by kvichans** [comment]
возможно - завтра

**Comment by Alexey-T** [comment]
Отменим- я начал делать Пас код

**Comment by kvichans** [comment]
Ок
Только это странно. Явно же: нужно будет потом допиливать эту функцию - поэтому ее место на уровне плагина
