### ISSUE TITLE
Wish: command “Align lines by indent”

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#84]
This cmd must make all lines in selection to same indent string. To the indent string of the first selected line

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Теперь я сомневаюсь, что действительно нужна отдельная команда. 

Это выравнивание можно получить за два шага (регулярно этим занимаюсь):
- Избавиться от всех пробельных, то есть прижать все строки _влево_ (несколько Shift+Tab)
- Восстановить сдвиг первой строки - остальные будут такие же (несколько Tab)

**Comment by Alexey-T** [comment]
Тут два недостатка- а) недо помнить какой был отступю поставить тот же. б) unindent_keeps_align - опц надо менять

**Comment by kvichans** [comment]
ок, будет

**Comment by Alexey-T** [comment]
Done
