### ISSUE TITLE
New cmds to show all bookmarks in tab/tabs

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#87]
Делаю две новые команды
![default](https://user-images.githubusercontent.com/7419630/36661158-9546b240-1aeb-11e8-91e9-d7ad6a3182fd.png)

Первая показывает все строки с марками, в том числе с нумерованными, в текущем табе
![default](https://user-images.githubusercontent.com/7419630/36661254-df2a9908-1aeb-11e8-81f7-78f9f48e1dbe.png)

Вторая показывает все строки с марками во всех табах
![default](https://user-images.githubusercontent.com/7419630/36661354-121c4ece-1aec-11e8-963a-8373b109f8f9.png)

В обоих случаях марка, ближайшая к текущей каретке, выделяется при вызове.
Конечно, есть переходы на указанные марки.

Есть пожелания/замечания?

----
Существующий диалог для выбора марки
![default](https://user-images.githubusercontent.com/7419630/36661743-3edc9ddc-1aed-11e8-806b-ea274ca190d7.png)
неудобен
- Нет строки для ввода поиска
- Номера строк выравнены не ту сторону
- Не отображается номер марки
- Нет версии для всех табов

**Comment by Alexey-T** [comment]
Замечаний пока нет, это нужные команды. Я поменяю показ номеров на пр сторону

**Comment by kvichans** [comment]
Добавил третью команду
![default](https://user-images.githubusercontent.com/7419630/36667621-8874965e-1aff-11e8-920d-a688987fb74b.png)
Она дает такой список
![default](https://user-images.githubusercontent.com/7419630/36667779-1c996698-1b00-11e8-825f-ceefa0968562.png)

**Comment by Alexey-T** [comment]
(tab=1-5) - ?

**Comment by kvichans** [comment]
Это пятый таб в первой группе.

Выложил в ГХ. Можно тестировать

**Comment by kvichans** [comment]
Сообразил :) "(tab=1-5)" нужно показывать только если включены _номера_ у табов

**Comment by kvichans** [comment]
Обновил ГХ, чтобы при умолчательном ui_tab_numbers=false отображалось так
![default](https://user-images.githubusercontent.com/7419630/36668509-9dc4d994-1b02-11e8-9846-218478181a81.png)

**Comment by Alexey-T** [comment]
Работает! спасибо.
