### ISSUE TITLE
New cmd "Open a recent file"

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_ext#89]
Делаю команду для выбора файла для открытия из тех, что хранятся в `history files.json`.
Вызов
![default](https://user-images.githubusercontent.com/7419630/36718671-af56de12-1bb3-11e8-9ae3-11a6df68a7c9.png)
дает такой выбор
![default](https://user-images.githubusercontent.com/7419630/36718758-f73816ec-1bb3-11e8-92a6-efd638a09137.png)
1. Отображаются только реально существующие, а не все из `history files.json`
2. Для каждого файла дано время модификации
3. Файлы сортированы по этому времени
4. Самое главное: есть фильтрация и по имени и по времени (так как это тоже текст)

Замечания/предложения?

**Comment by kvichans** [comment]
Рассматриваю следующие идеи
- Начинать список с тех же файлов, который видны из меню `Open recent` (это ключ `recent_files` из `history.json`)
- Использовать `~` для минимизации путей
- Показывать в том числе _пропавшие_ файлы - у них будет пустая дата

**Comment by Alexey-T** [comment]
- назвать опции плагина префиксом, напр. "cudaext_". Хорошо бы все опции этого плагина
- опция "сортировать по пути"
- выводить дату через / (опции не надо)

**Comment by kvichans** [comment]
Про сортировку. 
Есть такой трюк: в конец списка добавлю не файл, а команду - можно будет на лету менять сортировку

**Comment by Alexey-T** [comment]
хотел спросить про OptEditor. Вы сказали неделю делать. начали?

**Comment by kvichans** [comment]
Выложил в ГХ

**Comment by Alexey-T** [comment]
- имена месяцев на русском, надо на инглише.
- надо минимайзить пути по ~

**Comment by Alexey-T** [comment]
"Open recent file..."  без "а" лучше

**Comment by kvichans** [comment]
Названия месяцев.
- Не понимаю, почему у меня самого они английские. В пи-справке вижу
`%b   Locale’s abbreviated month name.`
ОС у меня русская. Локаль в питоне тоже 
`=locale.getdefaultlocale()`
`('ru_RU', 'cp1251')`

- А почему у вас должно быть по английски, если локаль русская?

Выложил в ГХ обновление
- Имя команды
- Сокращения до ~

**Comment by Alexey-T** [comment]
«Стало хорошо», спасибо

**Comment by kvichans** [comment]
Оставляем _месяцы_ и публикуем?

**Comment by Alexey-T** [comment]
Да

**Comment by kvichans** [comment]
Опубликовал
