### ISSUE TITLE
Cmd to handle words dups/ sort words

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#91]
Сложно ли добавить такой тул. то что делает этот сайт-
https://www.tracemyip.org/tools/remove-duplicate-words-in-text/
удаление повторов слов.

**Comment by kvichans** [comment]
Невнятное ТЗ. Что нужно?

**Comment by Alexey-T** [comment]
- Кмд- удалить все дубли слов во всем тексте (кроме первого вхожд. слова)
- Кмд- обратить порядок слов во всем тексте
- Кмд- сортировать слова по алф. во всем тексте

**Comment by Alexey-T** [comment]
Разделители- а) можно считать все пробелы, другие удалять б) считать что запятые, другие удалять. Детектить разделители по первому разделителю

**Comment by kvichans** [comment]
1. Как разделить на слова и что делать с символами, которые не в словах?
2. Кому это нужно? Выглядит искусственно. Такие задания дают на первых уроках программирования

**Comment by Alexey-T** [comment]
1- Резделители- см выше, Ок?
2- просили тут https://superuser.com/questions/1302218/is-there-a-way-to-automatically-remove-non-consecutive-duplicate-words-from-a-te

**Comment by kvichans** [comment]
2. Похоже, что кому-то нужен зачет по программированию. Зачем это в плагине?
3. Могу предложить решение на питоне. ИМХО этого достаточно

**Comment by Alexey-T** [comment]
Ok, отменим
