### ISSUE TITLE
QuickSearch panel?

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#92]
Как в Сине. можно сделать плагин. Чтобы показать панель, надо сделать "док" форме в окно Куд.

 DLG_DOCK: Docks (inserts) form into another form. Param "index" is handle of another form, and 0 means main CudaText form. Param "prop" can be: "L", "R", "T", "B" for sides left/right/top/bottom (default is bottom).

**Comment by kvichans** [comment]
В чем смысл новой панели? Я в Син ей не пользовался.
Чем она отличается от dock-режима основного окна диалога?

Я бы еще понял, если как в некоторых средах, строку поиска можно было набирать в гл.тулбаре и иметь простой хоткей для перемещения в это место и ESC возвращал назад. Но, видимо, запрос не про это.

**Comment by Alexey-T** [comment]
смысл? в ней не надо жать кнопки (Ентер и др.). она ищет по on_change.

**Comment by kvichans** [comment]
Ага. Это аналог поиска по странице в браузере. Так?

**Comment by kvichans** [comment]
Например в FF это выглядит так
![default](https://user-images.githubusercontent.com/7419630/37336886-bf1650f6-26c3-11e8-83bc-224f7664bc6a.png)

**Comment by Alexey-T** [comment]
Вы правы, это как в FF

**Comment by Alexey-T** [comment]
Можно слизать панель Хрома. иконки хорошие.

**Comment by kvichans** [comment]
В виде отдельной формы *почти все* то, о чем здесь говорили, [заработало](https://github.com/kvichans/cuda_ext/issues/106). Поиск не по ВВОД, а при каждом изменении сделать теперь не сложно. Так же как в ОпцРед добавлю настройку и будет 
- либо запоминание истории запросов и поиск по ВВОД
- либо поиск при каждом изменении, но без истории

Нужен ли DOCK-режим? Уже сейчас диалог имеет минимальные габариты и (например, мне) не мешает работать.

**Comment by kvichans** [comment]
> хорошо бы юзать новые кнопки- контрол button_ex. чтобы похоже на Куд

Поясните

**Comment by Alexey-T** [comment]
когда форма будет докед - хорошо бы была похожа на Куд поиск- значит надо

- красить фон формы (color) в текущ тему (тема читается через АПИ)
- делать такие же кнопки - контрол button_ex
- делать такой же ввод - контрол editor и св-во PROP_ONE_LINE

**Comment by Alexey-T** [comment]
как читать тему-
http://wiki.freepascal.org/CudaText_API#Themes
PROC_THEME_UI_DATA_GET

**Comment by kvichans** [comment]
Нет, мимикрировать под диалог ядра не буду.
Док-стиль попробую

**Comment by Alexey-T** [comment]
тогда док стиль на темной теме как будет смотреться.

**Comment by kvichans** [comment]
Темы для диалогов - это забота ядра

**Comment by Alexey-T** [comment]
тут такого нет, может через год-два
