### ISSUE TITLE
Cmd: Shorten selection

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_ext#94]
ST3 plugin SelectionTools:

-    Shortens the selection by one character both at the front and the back.
-   This can be useful when expanding the selection to quotes or brackets. Sometimes you don't want to select the quotes, or the lines containing the brackets

**Comment by kvichans** [comment]
Какая гадость. 
Нужно делать универсально. В Син мой плагин умел и расширять выделение (это перенесено в Куд) и сужать. Но делал он это с большим списком ситуаций, из которых _кавычки_ были только одной
